"""review.py — walk a finalized bundle, emit annotation layer.

Reads bundle.yml + raw-extract.md, splits by section markers, dispatches each
section to the adapter, writes editorial-review.md + editorial-annotations.jsonl
into _system/source/text/, and appends a `review:` block to bundle.yml.

DOES NOT modify raw-extract.md. (Source of truth must stay byte-faithful.)
DOES NOT switch bundle.yml.stage — that's seal.py's job.
"""
from __future__ import annotations
import json
import re
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from ..adapters.base import ReviewAdapter, Annotation
from ..adapters.urdu import SECTION_MARKER_RE


REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_GLOSSARY = REPO_ROOT / "tools" / "content_reviewer" / "data" / "ismaili-glossary.json"


def _read_bundle_yml_stage(bundle_yml: Path) -> str:
    for line in bundle_yml.read_text(encoding="utf-8").splitlines():
        if line.startswith("stage:"):
            return line.split(":", 1)[1].strip()
    return ""


def _strip_existing_review_block(text: str) -> str:
    """Remove any prior 'review:' block from bundle.yml (for idempotent re-runs)."""
    lines = text.splitlines()
    out: list[str] = []
    skipping = False
    for line in lines:
        if line.startswith("review:"):
            skipping = True
            continue
        if skipping:
            # Block is the 'review:' line plus all subsequent indented lines.
            if not line or line[0] in (" ", "\t"):
                continue
            skipping = False
        out.append(line)
    return "\n".join(out).rstrip() + "\n"


def _append_review_block(bundle_yml: Path, counts: dict, generated_at: str,
                          adapter_lang: str) -> None:
    text = _strip_existing_review_block(bundle_yml.read_text(encoding="utf-8"))
    lines: list[str] = [text.rstrip(), "", "review:"]
    lines.append(f"  generated_at: {generated_at}")
    lines.append(f"  adapter_language: {adapter_lang}")
    lines.append(f"  total: {counts['total']}")
    lines.append(f"  by_type:")
    for k in ("typo", "quran-uncited", "glossary", "sentence-completion", "needs-human-review"):
        lines.append(f"    {k}: {counts['by_type'].get(k, 0)}")
    lines.append(f"  by_confidence:")
    for k in ("high", "medium", "low"):
        lines.append(f"    {k}: {counts['by_confidence'].get(k, 0)}")
    bundle_yml.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _split_sections(raw_md: str) -> list[tuple[int, int, int, str, str]]:
    """Yield (position, section_id, raw_sort, label, body_text) tuples."""
    matches = list(SECTION_MARKER_RE.finditer(raw_md))
    out: list[tuple[int, int, int, str, str]] = []
    for i, m in enumerate(matches):
        position = int(m.group(1))
        section_id = int(m.group(2))
        raw_sort = int(m.group(3))
        label = m.group(4).strip()
        body_start = m.end()
        body_end = matches[i + 1].start() if i + 1 < len(matches) else len(raw_md)
        body = raw_md[body_start:body_end].strip("\n")
        out.append((position, section_id, raw_sort, label, body))
    return out


def _render_editorial_md(meta_header: dict,
                          per_section: list[tuple[tuple[int, int, str], list[Annotation]]],
                          ) -> str:
    """Human-readable per-section grouping of annotations."""
    lines: list[str] = []
    lines.append(f"# Editorial review — {meta_header.get('book_name', '')}\n")
    lines.append(f"_Generated by content_reviewer at {meta_header.get('generated_at', '')}._\n")
    lines.append(f"_Source: {meta_header.get('source', '')}; "
                 f"language: {meta_header.get('language', '')}._\n")
    lines.append("\nThis is the annotation layer — corrections proposed but NOT applied to "
                 "raw-extract.md. The source of truth remains byte-faithful. Human reviewer "
                 "decides which annotations to act on.\n")

    total = sum(len(a) for _, a in per_section)
    lines.append(f"\n**Total annotations:** {total}\n")
    if not total:
        lines.append("\n_No annotations emitted — the bundle passed the reviewer's checks._\n")
        return "\n".join(lines)

    for (pos, sid, label), anns in per_section:
        if not anns:
            continue
        lines.append(f"\n## Section {pos} — {label} (id={sid})\n")
        lines.append(f"_{len(anns)} annotation(s)._\n")
        for a in anns:
            lines.append(
                f"\n### [{a.type}] confidence={a.confidence} source={a.source}\n"
            )
            lines.append(f"**Excerpt:** `{a.original_excerpt}`\n")
            lines.append(f"**Annotation:** {a.annotation}\n")
            lines.append(f"**Rationale:** {a.rationale}\n")
    return "\n".join(lines) + "\n"


def review_book(
    adapter: ReviewAdapter,
    bundle_root: Path,
    glossary_path: Optional[Path] = None,
    quran_corpus=None,
) -> dict:
    """Entry point. Returns counts dict."""
    bundle_yml = bundle_root / "bundle.yml"
    text_dir = bundle_root / "_system" / "source" / "text"
    raw_extract = text_dir / "raw-extract.md"
    editorial_md = text_dir / "editorial-review.md"
    annotations_jsonl = text_dir / "editorial-annotations.jsonl"

    if not bundle_yml.exists():
        raise FileNotFoundError(f"bundle.yml not found at {bundle_yml}")
    stage = _read_bundle_yml_stage(bundle_yml)
    if stage == "reviewed":
        # Idempotent: already reviewed, skip.
        return {"total": 0, "by_type": {}, "by_confidence": {}, "skipped": True}
    if stage != "finalized":
        raise ValueError(
            f"Cannot review: bundle.yml.stage={stage!r} (expected 'finalized'). "
            f"Run `tools.source_extractor finalize` first."
        )

    glossary_path = glossary_path or DEFAULT_GLOSSARY
    glossary: dict
    if glossary_path.exists():
        glossary = json.loads(glossary_path.read_text(encoding="utf-8"))
    else:
        glossary = {"version": 0, "terms": []}

    raw_md = raw_extract.read_text(encoding="utf-8")
    section_blocks = _split_sections(raw_md)

    per_section: list[tuple[tuple[int, int, str], list[Annotation]]] = []
    all_annotations: list[Annotation] = []
    for (position, section_id, raw_sort, label, body) in section_blocks:
        anns = adapter.review_section(
            body, section_id, position, label, glossary, quran_corpus
        )
        per_section.append(((position, section_id, label), anns))
        all_annotations.extend(anns)

    # Counts
    by_type = Counter(a.type for a in all_annotations)
    by_conf = Counter(a.confidence for a in all_annotations)
    counts = {
        "total": len(all_annotations),
        "by_type": dict(by_type),
        "by_confidence": dict(by_conf),
    }

    # Book name (read from bundle.yml `book.name` line if present)
    book_name = ""
    source_name = ""
    for line in bundle_yml.read_text(encoding="utf-8").splitlines():
        if source_name == "" and line.startswith("source:"):
            source_name = line.split(":", 1)[1].strip()
        if line.startswith("  name:") and book_name == "":
            # First `  name:` after the `book:` header is the book name.
            # But `shelf:` block comes first. Find via simple state machine
            # below instead.
            pass
    # Simpler: re-parse for the book-block name.
    in_book = False
    for line in bundle_yml.read_text(encoding="utf-8").splitlines():
        if line.rstrip() == "book:":
            in_book = True
            continue
        if in_book:
            if line.startswith("  name:"):
                book_name = line.split(":", 1)[1].strip()
                break

    generated_at = datetime.now(timezone.utc).isoformat()

    # Write JSONL
    with annotations_jsonl.open("w", encoding="utf-8") as f:
        for a in all_annotations:
            f.write(json.dumps(a.to_dict(), ensure_ascii=False) + "\n")

    # Write human-readable MD
    editorial_md.write_text(
        _render_editorial_md(
            {
                "book_name": book_name,
                "source": source_name,
                "language": adapter.language,
                "generated_at": generated_at,
            },
            per_section,
        ),
        encoding="utf-8",
    )

    # Append review block to bundle.yml
    _append_review_block(bundle_yml, counts, generated_at, adapter.language)

    return counts
