-- 005_run_telemetry.sql — Per-phase cost and progress tracking.
-- Depends on: 003_book_metadata.sql (book_metadata table must exist first).

CREATE TABLE IF NOT EXISTS run_telemetry (
    run_id          TEXT PRIMARY KEY,      -- UUID generated by orchestrator
    book_slug       TEXT NOT NULL,         -- FK → book_metadata.slug (advisory)
    phase           TEXT NOT NULL,
    started_at      TEXT NOT NULL,         -- ISO-8601 datetime
    finished_at     TEXT,                  -- NULL until phase completes
    cost_usd        REAL  NOT NULL DEFAULT 0.0,
    atoms_extracted INTEGER NOT NULL DEFAULT 0,
    status          TEXT NOT NULL DEFAULT 'running'
                    CHECK (status IN ('running', 'completed', 'failed', 'skipped'))
);

CREATE INDEX IF NOT EXISTS idx_run_telemetry_book  ON run_telemetry (book_slug);
CREATE INDEX IF NOT EXISTS idx_run_telemetry_phase ON run_telemetry (phase);
CREATE INDEX IF NOT EXISTS idx_run_telemetry_status ON run_telemetry (status);
