import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

import { fold, matchExpression, parseQuery } from "../app/lib/search-fold";
import { snippetOf } from "../app/lib/search";

/**
 * The fifth mirror pair, pinned.
 *
 * `fold` exists twice: here in TypeScript, where it folds what a reader typed,
 * and in scripts/podcast/_listener_search.py, where it folded the passages at
 * publish time. If the two ever disagree, NOTHING raises — the index simply
 * stops answering, on the vowelled Arabic and Perso-Urdu spelling this library
 * is largely made of, and the results page looks like a complete answer to a
 * question it never asked.
 *
 * The fixtures are GENERATED by the Python. Regenerate them from it; a case
 * corrected by hand here would pin the mirror to the wrong half.
 */

const FIXTURES = JSON.parse(
  readFileSync(new URL("./fixtures/search-fold.fixtures.json", import.meta.url), "utf8"),
) as { cases: { in: string; out: string }[] };

describe("fold agrees with the publisher", () => {
  it("has fixtures to check against", () => {
    expect(FIXTURES.cases.length).toBeGreaterThan(20);
  });

  for (const { in: input, out } of FIXTURES.cases) {
    it(`folds ${JSON.stringify(input)}`, () => {
      expect(fold(input)).toBe(out);
    });
  }
});

describe("what the fold has to get right for this corpus", () => {
  it("folds vowelled Arabic to its skeleton", () => {
    expect(fold("اَلْكِرْمَانِيّ")).toBe(fold("الكرماني"));
  });

  it("folds the Urdu keyboard's letters onto the Arabic ones", () => {
    // The Sessions were transcribed on an Urdu layout. Unfolded, searching the
    // Arabic spelling misses every lecture — 1,448 Farsi yeh in the corpus.
    expect(fold("ولی")).toBe(fold("ولي"));
    expect(fold("کتاب")).toBe(fold("كتاب"));
    expect(fold("ہے")).toBe(fold("هے"));
  });

  it("folds the alif carriers together", () => {
    expect(fold("أبو")).toBe(fold("ابو"));
    expect(fold("إسلام")).toBe(fold("اسلام"));
  });

  it("folds scholarly transliteration onto the plain spelling the books use", () => {
    expect(fold("Ismaʿili")).toBe(fold("Ismaili"));
    expect(fold("Qurʾan")).toBe(fold("Quran"));
  });

  it("keeps word boundaries, unlike the provenance normaliser", () => {
    // `normalize_arabic` strips spaces to make one comparable skeleton. A search
    // index needs tokens, so this must not.
    expect(fold("بسم الله")).toContain(" ");
  });

  it("leaves nothing that could be read as query syntax", () => {
    // Every non-alphanumeric becomes a space, which is what makes the FTS
    // expression safe to build without escaping.
    expect(fold('a" OR b* : (c)')).toBe("a or b c");
    expect(fold("2:255")).toBe("2 255");
  });
});

describe("reading what was typed", () => {
  it("treats a reference as a reference, not as two numbers", () => {
    expect(parseQuery("2:255").reference).toEqual({ surah: 2, ayah: 255 });
    expect(parseQuery(" 41 : 53 ").reference).toEqual({ surah: 41, ayah: 53 });
    expect(parseQuery("q2:255").reference).toEqual({ surah: 2, ayah: 255 });
  });

  it("does not mistake ordinary text for a reference", () => {
    expect(parseQuery("intellect").reference).toBeNull();
    expect(parseQuery("chapter 2 verse 255").reference).toBeNull();
  });

  it("reports a query that folds away to nothing", () => {
    expect(parseQuery("!!!").empty).toBe(true);
    expect(parseQuery("").empty).toBe(true);
    expect(parseQuery("intellect").empty).toBe(false);
  });

  it("requires every term, and matches on prefix", () => {
    expect(matchExpression(["one", "two"])).toBe('"one"* AND "two"*');
  });

  it("aims at one column when the scope says so", () => {
    expect(matchExpression(["nur"], "arabic_fold")).toBe('arabic_fold : ("nur"*)');
  });

  it("has nothing to ask when there are no terms", () => {
    expect(matchExpression([])).toBeNull();
  });
});

describe("a snippet marks the word, not the punctuation around it", () => {
  it("leaves a trailing comma outside the highlight", () => {
    const segments = snippetOf("the anger of Allah, they think", ["allah"]);
    expect(segments.find((s) => s.hit)?.text).toBe("Allah");
    expect(segments.map((s) => s.text).join("")).toBe("the anger of Allah, they think");
  });

  it("keeps an apostrophe inside a word marked with it", () => {
    // `Allah's` is one word. Stripping the apostrophe would mark `Allah` and
    // leave `'s` hanging outside, which looks like a different kind of mistake.
    const segments = snippetOf("that Allah's anger is like ours", ["allah"]);
    expect(segments.find((s) => s.hit)?.text).toBe("Allah's");
  });

  it("marks several hits in one passage without swallowing the words between", () => {
    const segments = snippetOf("Allah and Allah was pleased", ["allah"]);
    expect(segments.filter((s) => s.hit).map((s) => s.text)).toEqual(["Allah", "Allah"]);
    expect(segments.map((s) => s.text).join("")).toBe("Allah and Allah was pleased");
  });

  it("never loses or reorders a character of the passage", () => {
    const source = "He said: Ubayd Allah (little servant of Allah), son of Abd Allah.";
    const segments = snippetOf(source, ["allah"]);
    expect(segments.map((s) => s.text).join("")).toBe(source);
  });
});

describe("marking never damages Arabic", () => {
  it("keeps a trailing shadda attached to the word it marks", () => {
    // A combining mark is not a letter, so a punctuation class of only
    // \p{L}\p{N} tore the `ّ` off `اَلْكِرْمَانِيّ` and marked the rest.
    const segments = snippetOf("قال اَلْكِرْمَانِيّ في كتابه", ["الكرماني"]);
    expect(segments.find((s) => s.hit)?.text).toBe("اَلْكِرْمَانِيّ");
  });

  it("returns the passage unchanged, mark or no mark", () => {
    const source = "بِسْمِ ٱللَّهِ ٱلرَّحْمَنِ ٱلرَّحِيمِ";
    expect(snippetOf(source, ["الرحمن"]).map((s) => s.text).join("")).toBe(source);
  });
});
