"""
Extract content from KAHSKOLE / KSESSIONS into per-book directories under
_workspace/kashkole-ksessions/extracted/<lang>/<NN-shelf>/<NN-book>/.

Each book directory mirrors the podcast pipeline's BOOK_DIR layout:

  <NN-book-slug>/
    _README.md
    _manifest.yml
    _system/
      source/
        <book-slug>.html              audit anchor — concatenated raw HTML
        text/
          raw-extract.md              Phase 0a output (markdown, Phase 0c-ready)
          _extraction-notes.md        skipped topics + caveats
    chapters/                          (Phase 0d will write here)
    episodes/                          (build script writes here)
    turboscribe/                       (human input)
    chapter-contracts/                 (Phase 0e contracts)

Proof-scope CLI:
  python -m scripts.extract kahskole --binder 1 --chapter 74
  python -m scripts.extract ksessions --group 5 --category 10
"""
from __future__ import annotations
import argparse, json, os, sys, textwrap
from datetime import datetime, timezone
from pathlib import Path

from scripts.db import query_json
from scripts.html_to_md import html_to_md
from scripts.slugify import slugify_english, slugify_urdu


REPO_ROOT = Path(__file__).resolve().parents[3]
EXTRACT_ROOT = REPO_ROOT / "_workspace" / "kashkole-ksessions" / "extracted"


# ---- shared emitter ---------------------------------------------------------

def emit_book(
    *,
    source: str,              # "kashkole" | "ksessions" — top-level folder name
    shelf_prefix: int,        # filesystem prefix for the category shelf
    shelf_slug: str,
    shelf_name: str,
    shelf_id: int,
    shelf_sort_key: int,
    shelf_label: str,         # human label for the shelf level (e.g., "binder", "group")
    book_prefix: int,         # filesystem prefix for this book
    book_slug: str,
    book_name: str,
    book_id: int,
    book_sort_key: int,
    book_label: str,          # human label for the book level (e.g., "chapter", "category")
    source_kind: str,         # "kahskole-chapter" | "ksessions-category"
    sections: list[dict],     # ordered list of {label, html, id, raw_sort, ...}
    section_label: str,       # human label for sections (e.g., "topic", "session")
    extraction_notes: list[str],
) -> Path:
    """Write the full BOOK_DIR. Returns the path."""
    shelf_dir = EXTRACT_ROOT / source / f"{shelf_prefix:02d}-{shelf_slug}"
    book_dir = shelf_dir / f"{book_prefix:02d}-{book_slug}"

    # Tree
    (book_dir / "_system" / "source" / "text").mkdir(parents=True, exist_ok=True)
    (book_dir / "chapters").mkdir(exist_ok=True)
    (book_dir / "episodes").mkdir(exist_ok=True)
    (book_dir / "turboscribe").mkdir(exist_ok=True)
    (book_dir / "chapter-contracts").mkdir(exist_ok=True)

    # 1. Audit anchor: concatenated raw HTML
    audit_anchor = book_dir / "_system" / "source" / f"{book_slug}.html"
    with audit_anchor.open("w", encoding="utf-8") as f:
        f.write(f"<!DOCTYPE html>\n<html><head><meta charset=\"utf-8\">\n")
        f.write(f"<title>{book_name}</title></head>\n<body>\n")
        f.write(f"<!-- AUDIT ANCHOR — concatenated raw HTML from {source_kind} -->\n")
        f.write(f"<!-- shelf: {shelf_name} (id={shelf_id})  book: {book_name} (id={book_id}) -->\n\n")
        for i, s in enumerate(sections, 1):
            f.write(f"\n<hr><!-- section {i} | id={s['id']} | raw_sort={s['raw_sort']} | label={s['label']} -->\n")
            f.write(s.get("html") or "<!-- no content -->")
            f.write("\n")
        f.write("\n</body></html>\n")

    # 2. raw-extract.md — Phase 0a output
    raw_extract = book_dir / "_system" / "source" / "text" / "raw-extract.md"
    with raw_extract.open("w", encoding="utf-8") as f:
        f.write(f"# {book_name}\n\n")
        f.write(f"*Source: {source_kind}, shelf {shelf_id} ({shelf_name}), "
                f"book {book_id}. {len(sections)} sections.*\n\n")
        for i, s in enumerate(sections, 1):
            f.write(f"<!-- section {i} (id={s['id']}, raw_sort={s['raw_sort']}): {s['label']} -->\n\n")
            md = html_to_md(s.get("html") or "")
            if not md.strip():
                f.write(f"*(no content — see _extraction-notes.md)*\n\n")
            else:
                f.write(md)
                if not md.endswith("\n\n"):
                    f.write("\n\n")

    # 3. _manifest.yml
    manifest = book_dir / "_manifest.yml"
    yaml_lines = [
        f"# generated by scripts/extract.py at {datetime.now(timezone.utc).isoformat()}",
        f"source: {source}",
        f"source_kind: {source_kind}",
        f"shelf:",
        f"  kind: {shelf_label}",
        f"  id: {shelf_id}",
        f"  name: {_yaml_str(shelf_name)}",
        f"  sort_key: {shelf_sort_key}",
        f"  slug: {shelf_slug}",
        f"  prefix: {shelf_prefix:02d}",
        f"book:",
        f"  kind: {book_label}",
        f"  id: {book_id}",
        f"  name: {_yaml_str(book_name)}",
        f"  sort_key: {book_sort_key}",
        f"  slug: {book_slug}",
        f"  prefix: {book_prefix:02d}",
        f"sections:",
        f"  kind: {section_label}",
        f"  items:",
    ]
    for i, s in enumerate(sections, 1):
        yaml_lines.append(f"    - position: {i}")
        yaml_lines.append(f"      id: {s['id']}")
        yaml_lines.append(f"      raw_sort: {s['raw_sort']}")
        yaml_lines.append(f"      label: {_yaml_str(s['label'])}")
        yaml_lines.append(f"      has_content: {bool(s.get('html'))}")
        if 'extras' in s:
            for k, v in s['extras'].items():
                yaml_lines.append(f"      {k}: {_yaml_value(v)}")
    manifest.write_text("\n".join(yaml_lines) + "\n", encoding="utf-8")

    # 4. _extraction-notes.md
    notes = book_dir / "_system" / "source" / "text" / "_extraction-notes.md"
    with notes.open("w", encoding="utf-8") as f:
        f.write(f"# Extraction notes — {book_name}\n\n")
        f.write(f"Generated {datetime.now(timezone.utc).isoformat()}.\n\n")
        if extraction_notes:
            for n in extraction_notes:
                f.write(f"- {n}\n")
        else:
            f.write("_No notable issues during extraction._\n")

    # 5. _README.md
    readme = book_dir / "_README.md"
    section_count = len(sections)
    with_content = sum(1 for s in sections if s.get("html"))
    readme.write_text(textwrap.dedent(f"""\
        # {book_name}

        | | |
        |---|---|
        | Source database | `{source.upper()}` |
        | {shelf_label.capitalize()} (shelf) | {shelf_name} (id {shelf_id}, sort_key {shelf_sort_key}) |
        | {book_label.capitalize()} (this book) | id {book_id}, sort_key {book_sort_key} |
        | {section_label.capitalize()}s (sections) | {section_count} ({with_content} with content) |
        | Generated | {datetime.now(timezone.utc).isoformat()} |

        ## Layout

        - `_system/source/{book_slug}.html` — audit anchor (concatenated raw HTML; never modified)
        - `_system/source/text/raw-extract.md` — Phase 0a output (clean markdown)
        - `_system/source/text/_extraction-notes.md` — skipped sections + caveats
        - `_manifest.yml` — DB IDs, sort keys, slugs (for traceability)
        - `chapters/` — Phase 0d will segment `raw-extract.md` into per-podcast-chapter files here
        - `episodes/` — `build_episode_txt.py` will write the customize-prompt episode files here
        - `turboscribe/` — human drops post-NotebookLM transcripts here
        - `chapter-contracts/` — Phase 0e per-chapter contract YAMLs

        ## Arabic markers

        Every Arabic word, phrase, or quote in `raw-extract.md` is wrapped in `⟪ar:…⟫` (inline)
        or `⟪ar-quote:…⟫` (quoted passage). Phase 0c grep these markers to build the per-book
        phonetic index — do not strip them during Phase 0b refinement.
        """), encoding="utf-8")

    return book_dir


def _yaml_str(s: str) -> str:
    if not s:
        return "''"
    if any(c in s for c in ":#\"'\n[]{},&*!|>%@`"):
        return json.dumps(s, ensure_ascii=False)
    return s


def _yaml_value(v):
    if isinstance(v, bool): return "true" if v else "false"
    if isinstance(v, (int, float)): return str(v)
    if v is None: return "null"
    return _yaml_str(str(v))


# ---- KAHSKOLE adapter -------------------------------------------------------

def extract_kahskole_chapter(binder_id: int, chapter_id: int) -> Path:
    """Extract one KAHSKOLE Chapter as a BOOK_DIR."""
    binder = query_json("KASHKOLE", f"""
        SELECT BinderID AS id, BinderName AS name, BinderOrder AS sort_key
        FROM Binders WHERE BinderID = {binder_id} FOR JSON PATH;""")[0]

    bc = query_json("KASHKOLE", f"""
        SELECT bc.BinderChapterOrder AS book_sort_key, c.ChapterID AS id, c.ChapterName AS name
        FROM BinderChapters bc JOIN Chapters c ON c.ChapterID = bc.ChapterID
        WHERE bc.BinderID = {binder_id} AND bc.ChapterID = {chapter_id} FOR JSON PATH;""")[0]

    topics = query_json("KASHKOLE", f"""
        SELECT ct.ChapterTopicOrder AS raw_sort,
               t.TopicID AS id, t.TopicName AS name, t.TopicNameEnglish AS name_en,
               td.TopicUnicode AS html
        FROM ChapterTopics ct
        JOIN Topics t ON t.TopicID = ct.TopicID
        LEFT JOIN TopicDataUnicode td ON td.TopicID = t.TopicID
        WHERE ct.ChapterID = {chapter_id}
        ORDER BY ct.ChapterTopicOrder
        FOR JSON PATH;""")

    sections: list[dict] = []
    notes: list[str] = []
    for t in topics:
        label = t["name"] or f"Topic {t['id']}"
        if t.get("html"):
            sections.append({
                "label": label, "id": t["id"], "raw_sort": t["raw_sort"],
                "html": t["html"],
                "extras": {"topic_name_en": t.get("name_en")} if t.get("name_en") else {},
            })
        else:
            # Image-only or empty topic
            notes.append(
                f"Topic T{t['id']} ({label}) at order {t['raw_sort']} has no "
                f"Unicode content — likely image-only (TopicData PNG path). Skipped."
            )
            sections.append({
                "label": label, "id": t["id"], "raw_sort": t["raw_sort"], "html": None,
                "extras": {"image_only": True},
            })

    # Determine shelf prefix (1-based ordering of binders by BinderOrder)
    all_binders = query_json("KASHKOLE",
        "SELECT BinderID AS id, BinderOrder AS sort_key FROM Binders ORDER BY BinderOrder FOR JSON PATH;")
    shelf_prefix = [b["id"] for b in all_binders].index(binder_id) + 1

    # Determine book prefix (1-based ordering of chapters within this binder)
    all_in_binder = query_json("KASHKOLE", f"""
        SELECT ChapterID AS id FROM BinderChapters WHERE BinderID = {binder_id}
        ORDER BY BinderChapterOrder FOR JSON PATH;""")
    book_prefix = [c["id"] for c in all_in_binder].index(chapter_id) + 1

    return emit_book(
        source="kashkole",
        shelf_prefix=shelf_prefix,
        shelf_slug=slugify_urdu(binder["name"], binder["id"]),
        shelf_name=binder["name"],
        shelf_id=binder["id"],
        shelf_sort_key=binder["sort_key"],
        shelf_label="binder",
        book_prefix=book_prefix,
        book_slug=slugify_urdu(bc["name"], bc["id"]),
        book_name=bc["name"],
        book_id=bc["id"],
        book_sort_key=bc["book_sort_key"],
        book_label="chapter",
        source_kind="kahskole-chapter",
        sections=sections,
        section_label="topic",
        extraction_notes=notes,
    )


# ---- KSESSIONS adapter ------------------------------------------------------

def extract_ksessions_category(group_id: int, category_id: int) -> Path:
    """Extract one KSESSIONS Category as a BOOK_DIR."""
    group = query_json("KSESSIONS", f"""
        SELECT GroupID AS id, GroupName AS name, GroupID AS sort_key
        FROM Groups WHERE GroupID = {group_id} FOR JSON PATH;""")[0]

    cat = query_json("KSESSIONS", f"""
        SELECT CategoryID AS id, CategoryName AS name, SortOrder AS book_sort_key
        FROM Categories WHERE CategoryID = {category_id} FOR JSON PATH;""")[0]

    sessions = query_json("KSESSIONS", f"""
        SELECT s.Sequence AS raw_sort, s.SessionID AS id, s.SessionName AS name,
               s.Description AS description, s.SessionDate AS session_date,
               s.IsActive AS is_active,
               st.Transcript AS html
        FROM Sessions s
        LEFT JOIN SessionTranscripts st ON st.SessionID = s.SessionID
        WHERE s.GroupID = {group_id} AND s.CategoryID = {category_id}
        ORDER BY s.Sequence
        FOR JSON PATH;""")

    sections: list[dict] = []
    notes: list[str] = []
    for s in sessions:
        label = s["name"] or f"Session {s['id']}"
        extras = {"is_active_in_source_db": bool(s.get("is_active"))}
        if s.get("session_date"):
            extras["session_date"] = s["session_date"]
        if s.get("description"):
            extras["description"] = s["description"]
        if not s.get("is_active"):
            notes.append(
                f"Session S{s['id']} ({label}) at sequence {s['raw_sort']} is "
                f"marked IsActive=0 in the source DB. Content extracted anyway."
            )
        if s.get("html"):
            sections.append({
                "label": label, "id": s["id"], "raw_sort": s["raw_sort"],
                "html": s["html"], "extras": extras,
            })
        else:
            notes.append(
                f"Session S{s['id']} ({label}) at sequence {s['raw_sort']} "
                f"has no transcript content. Empty section emitted."
            )
            sections.append({
                "label": label, "id": s["id"], "raw_sort": s["raw_sort"], "html": None,
                "extras": {**extras, "no_transcript": True},
            })

    # Shelf prefix: 1-based ordering of groups by GroupID (per locked decision)
    all_groups = query_json("KSESSIONS",
        "SELECT GroupID AS id FROM Groups ORDER BY GroupID FOR JSON PATH;")
    shelf_prefix = [g["id"] for g in all_groups].index(group_id) + 1

    # Book prefix: 1-based ordering of categories within this group by SortOrder
    cats_in_group = query_json("KSESSIONS", f"""
        SELECT CategoryID AS id FROM Categories
        WHERE GroupID = {group_id} ORDER BY SortOrder FOR JSON PATH;""")
    book_prefix = [c["id"] for c in cats_in_group].index(category_id) + 1

    return emit_book(
        source="ksessions",
        shelf_prefix=shelf_prefix,
        shelf_slug=slugify_english(group["name"]),
        shelf_name=group["name"],
        shelf_id=group["id"],
        shelf_sort_key=group["sort_key"],
        shelf_label="group",
        book_prefix=book_prefix,
        book_slug=slugify_english(cat["name"]),
        book_name=cat["name"],
        book_id=cat["id"],
        book_sort_key=cat["book_sort_key"],
        book_label="category",
        source_kind="ksessions-category",
        sections=sections,
        section_label="session",
        extraction_notes=notes,
    )


# ---- CLI --------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)

    k = sub.add_parser("kahskole")
    k.add_argument("--binder", type=int, required=True)
    k.add_argument("--chapter", type=int, required=True)

    s = sub.add_parser("ksessions")
    s.add_argument("--group", type=int, required=True)
    s.add_argument("--category", type=int, required=True)

    args = ap.parse_args()
    if args.cmd == "kahskole":
        path = extract_kahskole_chapter(args.binder, args.chapter)
    else:
        path = extract_ksessions_category(args.group, args.category)
    print(f"WROTE: {path}")


if __name__ == "__main__":
    main()
