"""Bundle layout helpers.

The bundle is a self-contained directory that the podcast pipeline will
intake via a forthcoming `intake_book.py --from-bundle <path>` flag (Phase D).
It mirrors the shape the pipeline expects under `content/drafts/<slug>/_system/source/`
so intake can drop it in with minimal transformation.

Layout:

  <extract_root>/<source>/<NN-shelf>/<MM-book>/
    _README.md                              ← human-readable summary
    bundle.yml                              ← bundle manifest (read by intake)
    _system/
      source/
        <book-slug>.html                    ← audit anchor: concatenated raw HTML
        text/
          raw-extract.md                    ← Phase 0a output (source language)
          _extraction-notes.md              ← skipped sections + caveats
          _provenance.json                  ← podcast.ingest-source/v1 schema
        images/
          001.png, 001.json                 ← decoded bytes + Stage B sidecar
          002.png, 002.json
          ...
          vision-tasks.json                 ← Stage B work queue

During Stage A (prepare), `raw-extract.md` is written as `raw-extract.md.draft`
with `{{IMG:NNN}}` placeholders. Stage C (finalize) substitutes and drops the
`.draft` suffix.
"""
from __future__ import annotations
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional
import json

from .adapters.base import BookMeta, AdapterLabels, Section
from .yaml_lite import yaml_str


BUNDLE_SCHEMA_VERSION = 1
PROVENANCE_SCHEMA = "podcast.ingest-source/v1"


@dataclass(frozen=True)
class BundlePaths:
    """All paths a stage needs inside one bundle."""
    root: Path                  # the BOOK_DIR
    readme: Path                # _README.md
    bundle_yml: Path            # bundle.yml
    system_source: Path         # _system/source/
    audit_anchor_html: Path     # _system/source/<book-slug>.html
    text_dir: Path              # _system/source/text/
    raw_extract_draft: Path     # text/raw-extract.md.draft
    raw_extract_final: Path     # text/raw-extract.md
    extraction_notes: Path      # text/_extraction-notes.md
    provenance: Path            # text/_provenance.json
    images_dir: Path            # _system/source/images/
    vision_tasks: Path          # images/vision-tasks.json


def bundle_paths(extract_root: Path, meta: BookMeta) -> BundlePaths:
    """Compute all bundle paths for a given (source, shelf, book)."""
    root = (
        extract_root / meta.source_name
        / f"{meta.shelf_prefix:02d}-{meta.shelf_slug}"
        / f"{meta.book_prefix:02d}-{meta.book_slug}"
    )
    system_source = root / "_system" / "source"
    text_dir = system_source / "text"
    images_dir = system_source / "images"
    return BundlePaths(
        root=root,
        readme=root / "_README.md",
        bundle_yml=root / "bundle.yml",
        system_source=system_source,
        audit_anchor_html=system_source / f"{meta.book_slug}.html",
        text_dir=text_dir,
        raw_extract_draft=text_dir / "raw-extract.md.draft",
        raw_extract_final=text_dir / "raw-extract.md",
        extraction_notes=text_dir / "_extraction-notes.md",
        provenance=text_dir / "_provenance.json",
        images_dir=images_dir,
        vision_tasks=images_dir / "vision-tasks.json",
    )


def ensure_bundle_dirs(paths: BundlePaths) -> None:
    """mkdir -p for every directory in the bundle."""
    paths.text_dir.mkdir(parents=True, exist_ok=True)
    paths.images_dir.mkdir(parents=True, exist_ok=True)


def write_bundle_yml(
    paths: BundlePaths,
    meta: BookMeta,
    labels: AdapterLabels,
    sections_meta: list[dict],
    image_count: int,
    stage: str = "prepared",
) -> None:
    """Bundle manifest at root. The future intake_book.py --from-bundle reads this
    first to learn slug, source_language, branch prefix hint, etc."""
    lines = [
        f"# bundle manifest — read by intake_book.py --from-bundle",
        f"# generated by tools/source_extractor at "
        f"{datetime.now(timezone.utc).isoformat()}",
        f"bundle_schema_version: {BUNDLE_SCHEMA_VERSION}",
        f"source: {meta.source_name}",
        f"source_language: {meta.source_language}",
        f"stage: {stage}",
        f"shelf:",
        f"  kind: {labels.shelf_label}",
        f"  id: {meta.shelf_id}",
        f"  name: {yaml_str(meta.shelf_name)}",
        f"  sort_key: {meta.shelf_sort_key}",
        f"  slug: {meta.shelf_slug}",
        f"  prefix: {meta.shelf_prefix:02d}",
        f"book:",
        f"  kind: {labels.book_label}",
        f"  id: {meta.book_id}",
        f"  name: {yaml_str(meta.book_name)}",
        f"  sort_key: {meta.book_sort_key}",
        f"  slug: {meta.book_slug}",
        f"  prefix: {meta.book_prefix:02d}",
        f"# pipeline-side intake will use these as suggestions; final slug/branch",
        f"# is intake's call (it must check for collisions in content/drafts/).",
        f"pipeline_hints:",
        f"  suggested_slug: {meta.source_name}-{meta.shelf_slug}-{meta.book_slug}",
        f"  suggested_branch_prefix: lecture",
        f"counts:",
        f"  sections: {len(sections_meta)}",
        f"  sections_with_content: "
        f"{sum(1 for s in sections_meta if s['has_content'])}",
        f"  inline_images: {image_count}",
        f"  curated_citation_refs: "
        f"{sum(len(s.get('curated_citations', [])) for s in sections_meta)}",
        f"sections:",
        f"  kind: {labels.section_label}",
        f"  items:",
    ]
    for s in sections_meta:
        lines.append(f"    - position: {s['position']}")
        lines.append(f"      id: {s['id']}")
        lines.append(f"      raw_sort: {s['raw_sort']}")
        lines.append(f"      label: {yaml_str(s['label'])}")
        if s.get("name_en"):
            lines.append(f"      name_en: {yaml_str(s['name_en'])}")
        lines.append(f"      has_content: {str(s['has_content']).lower()}")
        lines.append(f"      image_count_inline: {s['image_count_inline']}")
        if s.get("curated_citations"):
            lines.append(f"      curated_citations:")
            for c in s["curated_citations"]:
                lines.append(
                    f"        - {{ surah: {c['surah']}, ayat: {c['ayat']} }}"
                )
        else:
            lines.append(f"      curated_citations: []")
    paths.bundle_yml.write_text("\n".join(lines) + "\n", encoding="utf-8")


def update_bundle_yml_stage(
    paths: BundlePaths,
    new_stage: str,
    finalize_block: Optional[dict] = None,
) -> None:
    """Mutate bundle.yml: switch stage line; optionally append a finalize: block."""
    text = paths.bundle_yml.read_text(encoding="utf-8")
    out_lines = []
    for line in text.splitlines():
        if line.startswith("stage: "):
            out_lines.append(f"stage: {new_stage}")
        else:
            out_lines.append(line)
    if finalize_block:
        out_lines.append("")
        out_lines.append("finalize:")
        for k, v in finalize_block.items():
            if isinstance(v, list):
                if not v:
                    out_lines.append(f"  {k}: []")
                else:
                    out_lines.append(f"  {k}:")
                    for item in v:
                        out_lines.append(f"    - {_render_inline_dict(item)}")
            elif isinstance(v, dict):
                out_lines.append(f"  {k}: {_render_inline_dict(v)}")
            else:
                out_lines.append(f"  {k}: {v}")
    paths.bundle_yml.write_text("\n".join(out_lines) + "\n", encoding="utf-8")


def _render_inline_dict(d: dict) -> str:
    parts = []
    for k, v in d.items():
        if isinstance(v, str):
            parts.append(f"{k}: {yaml_str(v)}")
        else:
            parts.append(f"{k}: {v}")
    return "{ " + ", ".join(parts) + " }"


def write_provenance(
    paths: BundlePaths,
    meta: BookMeta,
    labels: AdapterLabels,
    *,
    db_name: str,
    section_query_count: int,
    stage: str = "prepared",
) -> None:
    """Write _provenance.json — same schema as PDF-source provenance,
    but with source.kind="sql" and an extraction.sql_source block instead
    of doc_intelligence/translator."""
    doc = {
        "schema": PROVENANCE_SCHEMA,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source": {
            "kind": "sql",
            "name": meta.source_name,
            "db": db_name,
            "container": "kashkole-mssql",
        },
        "book_slug": meta.book_slug,
        "book_dir": str(paths.root),
        "source_language": meta.source_language,
        "extraction": {
            "tool": "tools.source_extractor",
            "shelf": {
                "kind": labels.shelf_label,
                "id": meta.shelf_id,
                "name": meta.shelf_name,
            },
            "book": {
                "kind": labels.book_label,
                "id": meta.book_id,
                "name": meta.book_name,
            },
            "section_query_count": section_query_count,
            "stage": stage,
        },
        "outputs": {
            "raw_extract": str(paths.raw_extract_final.relative_to(paths.root)),
            "extraction_notes": str(paths.extraction_notes.relative_to(paths.root)),
            "audit_anchor_html": str(paths.audit_anchor_html.relative_to(paths.root)),
            "images_dir": str(paths.images_dir.relative_to(paths.root)),
        },
    }
    paths.provenance.write_text(
        json.dumps(doc, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )


def update_provenance_finalize(
    paths: BundlePaths,
    *,
    image_classifications: dict[str, str],
    citation_replacements: int,
) -> None:
    """Append finalize block to _provenance.json."""
    doc = json.loads(paths.provenance.read_text(encoding="utf-8"))
    doc["extraction"]["stage"] = "finalized"
    doc["finalize"] = {
        "finalized_at": datetime.now(timezone.utc).isoformat(),
        "images_classified": image_classifications,
        "inline_citations_resolved": citation_replacements,
    }
    paths.provenance.write_text(
        json.dumps(doc, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )


def write_readme(
    paths: BundlePaths,
    meta: BookMeta,
    labels: AdapterLabels,
    section_count: int,
    sections_with_content: int,
    image_count: int,
) -> None:
    """Human-readable bundle README."""
    body = (
        f"# {meta.book_name}\n\n"
        f"Source-extractor bundle for the podcast pipeline.\n"
        f"After intake (`intake_book.py --from-bundle <this-dir>`), the\n"
        f"pipeline picks up at Phase 0b (or 0a-translate if "
        f"source_language ≠ 'en').\n\n"
        f"| | |\n"
        f"|---|---|\n"
        f"| Source database | `{meta.source_name.upper()}` |\n"
        f"| Source language | `{meta.source_language}` |\n"
        f"| {labels.shelf_label.capitalize()} (shelf) | "
        f"{meta.shelf_name} (id {meta.shelf_id}, "
        f"sort_key {meta.shelf_sort_key}) |\n"
        f"| {labels.book_label.capitalize()} (this book) | "
        f"id {meta.book_id}, sort_key {meta.book_sort_key} |\n"
        f"| {labels.section_label.capitalize()}s (sections) | "
        f"{section_count} ({sections_with_content} with content) |\n"
        f"| Inline images | {image_count} |\n\n"
        f"## Layout\n\n"
        f"- `bundle.yml` — manifest read by intake (slug, source_language, "
        f"sections list)\n"
        f"- `_system/source/{meta.book_slug}.html` — audit anchor "
        f"(concatenated raw HTML; never modified)\n"
        f"- `_system/source/text/raw-extract.md` — Phase 0a output "
        f"(clean markdown, source language)\n"
        f"- `_system/source/text/_extraction-notes.md` — skipped sections + "
        f"caveats\n"
        f"- `_system/source/text/_provenance.json` — "
        f"`{PROVENANCE_SCHEMA}` provenance record\n"
        f"- `_system/source/images/` — decoded PNG + per-image vision sidecar "
        f"JSON\n\n"
        f"## Arabic markers\n\n"
        f"Every Arabic word, phrase, or quote in `raw-extract.md` is wrapped "
        f"in `⟪ar:…⟫` (inline) or `⟪ar-quote:…⟫` (quoted passage). "
        f"Phase 0c grep these markers to build the per-book phonetic index — "
        f"do not strip them during refinement.\n"
    )
    paths.readme.write_text(body, encoding="utf-8")


def write_audit_anchor_html(
    paths: BundlePaths,
    meta: BookMeta,
    labels: AdapterLabels,
    sections: list[Section],
) -> None:
    """Write the concatenated raw HTML — provenance only, never modified."""
    parts: list[str] = []
    parts.append('<!DOCTYPE html>\n<html><head><meta charset="utf-8">\n')
    parts.append(f"<title>{meta.book_name}</title></head>\n<body>\n")
    parts.append(
        f"<!-- AUDIT ANCHOR — concatenated raw HTML from "
        f"{meta.source_name}-{labels.book_label} -->\n"
    )
    parts.append(
        f"<!-- {labels.shelf_label}: {meta.shelf_name} (id={meta.shelf_id})  "
        f"{labels.book_label}: {meta.book_name} (id={meta.book_id}) -->\n\n"
    )
    for i, s in enumerate(sections, 1):
        parts.append(
            f"\n<hr><!-- section {i} | id={s.id} | raw_sort={s.raw_sort} | "
            f"label={s.label} -->\n"
        )
        parts.append(s.html or "<!-- no content -->")
        parts.append("\n")
    parts.append("\n</body></html>\n")
    paths.audit_anchor_html.write_text("".join(parts), encoding="utf-8")


def write_extraction_notes(
    paths: BundlePaths,
    meta: BookMeta,
    notes: list[str],
) -> None:
    """Write _extraction-notes.md."""
    lines = [
        f"# Extraction notes — {meta.book_name}\n",
        f"Generated {datetime.now(timezone.utc).isoformat()}.\n",
    ]
    if notes:
        for n in notes:
            lines.append(f"- {n}\n")
    else:
        lines.append("_No notable issues during extraction._\n")
    paths.extraction_notes.write_text("".join(lines), encoding="utf-8")
