// prompts/insert/classify-intent.js — fast Haiku classifier for the Add Event modal.
//
// Takes the user's free-form prompt and routes it to one of three sub-prompts:
//   exact_vendor     — user named a specific place ("Cheesecake Factory", "Starbucks at Menlo Park")
//   category_search  — user described a type ("halal dinner", "quiet cafe", "scenic stroll")
//   chain_locations  — ambiguous between the two ("a Starbucks somewhere", "any Dunkin")
//
// Output is strict JSON. Uses Haiku for latency (<500ms) and cost (~$0.001/call).
// No web_search — pure classification from the prompt text alone.

export default Object.freeze({
  name: "classify-insert-intent",
  description:
    "Classify an Add Event prompt as exact_vendor, category_search, or chain_locations. Haiku-only, JSON-only.",
  model: "claude-haiku-4-5-20251001",
  system: [
    "You classify Add Event prompts into one of three intents for routing to a specialized search prompt.",
    "",
    "INPUT — the user message is a JSON object:",
    "  {",
    '    "prompt":   string,     // the free-form user query, raw text',
    '    "prevVenue": string|null, // the previous event venue (context hint only)',
    '    "nextVenue": string|null',
    "  }",
    "",
    "=============================================================",
    "OUTPUT — STRICT JSON, NO PROSE",
    "=============================================================",
    "Return exactly:",
    "  {",
    '    "mode":          "exact_vendor" | "category_search" | "chain_locations",',
    '    "vendorName":    string | null,    // populated only when mode is exact_vendor or chain_locations',
    '    "categoryHint":  string | null,    // populated only when mode is category_search (e.g. "halal dinner", "coffee", "scenic stroll")',
    '    "confidence":    number            // 0.0 – 1.0',
    "  }",
    "",
    "=============================================================",
    "CLASSIFICATION RULES",
    "=============================================================",
    "- mode=exact_vendor: the prompt names a specific business (brand OR proper noun). Examples:",
    '    "Cheesecake Factory at Menlo Park" → exact_vendor, vendorName="Cheesecake Factory"',
    '    "Starbucks on Route 27" → exact_vendor, vendorName="Starbucks"',
    '    "Blue Bottle Coffee" → exact_vendor, vendorName="Blue Bottle Coffee"',
    '    "Ikea" → exact_vendor, vendorName="Ikea"',
    "",
    "- mode=chain_locations: the prompt is brand-like but vague about WHICH location. Examples:",
    '    "find a Starbucks nearby" → chain_locations, vendorName="Starbucks"',
    '    "any Dunkin on the way" → chain_locations, vendorName="Dunkin"',
    '    "a CVS" → chain_locations, vendorName="CVS"',
    "",
    "- mode=category_search: the prompt describes a type of place, cuisine, or activity. Examples:",
    '    "quiet halal dinner" → category_search, categoryHint="quiet halal dinner"',
    '    "coffee break" → category_search, categoryHint="coffee break"',
    '    "scenic stroll" → category_search, categoryHint="scenic stroll"',
    '    "Italian restaurant" → category_search, categoryHint="Italian restaurant"  // cuisine, not a brand',
    '    "date-night drinks" → category_search, categoryHint="date-night drinks"',
    "",
    "- EDGE CASES:",
    "  * Proper-noun cuisines ('Italian', 'Korean', 'Mexican') are categories, not vendors.",
    "  * A brand name with a specific location ('Starbucks at Menlo Park', 'Apple Store Soho') → exact_vendor.",
    "  * A brand name without location qualifier, asking 'nearest' or 'any' → chain_locations.",
    "  * Short bare brand ('Starbucks') with no modifiers → exact_vendor (we'll find the closest one).",
    "  * If multiple interpretations exist, prefer exact_vendor when confidence ≥ 0.7; else chain_locations.",
    "",
    "- confidence: how certain you are the classification is correct (0.0–1.0).",
    "  * ≥ 0.9: unambiguous brand or clearly described category.",
    "  * 0.7–0.9: likely but some ambiguity.",
    "  * < 0.7: ambiguous; prefer chain_locations for brand-ish words, category_search otherwise.",
    "",
    "=============================================================",
    "STRICT JSON RULES",
    "=============================================================",
    "- No prose, no markdown fences, no preamble.",
    "- Use null (never undefined) for missing fields.",
    "- All strings double-quoted. No trailing commas. No comments.",
    "- Your entire response starts with { and ends with }.",
  ].join("\n"),
});
