-- What a READER accumulates: where they got to, what they marked, what they wrote.
--
-- Everything before this migration is about the library — what exists and who may
-- open it. This is the first per-person state in the database, and three rules
-- shape all four tables.
--
--   1. KEYED ON EMAIL, never on user.id. Not a stylistic match with `invite` and
--      `access_grant`: `Viewer` (app/middleware/session.ts) deliberately does not
--      carry a user id, Better Auth may create a fresh `user` row for the same
--      person, and every email that reaches a key column has already been through
--      `normalizeEmail`. One comparator, everywhere, or `a.b@gmail.com` and
--      `ab@gmail.com` accumulate two separate sets of notes.
--
--   2. NO FOREIGN KEY TO `chapter`, and that is the important one.
--      `publish_to_listener.py` re-publishes a book with `DELETE FROM chapter
--      WHERE slug = …` followed by re-inserts. A FK with cascade would erase
--      everyone's highlights every time a book is re-composed — which is a normal,
--      frequent event here. `(slug, anchor_key)` is stored as loose columns,
--      exactly as `episode_chapter` already does it, so a re-publish lands the
--      chapter back on the row its annotations already point at.
--
--   3. SOFT DELETE on the two tables a device can create rows in. The reader
--      writes through a localStorage outbox, so a delete has to be replayable: a
--      phone that was offline when a highlight was removed must be able to flush
--      "remove this" rather than re-create it. `deleted_at` is what makes the
--      outbox idempotent. Progress rows are last-writer-wins and need none.
--
-- No `status`/`open_to_all` analogue exists here. Nothing in this migration is a
-- privilege bit; a row grants nobody the right to read anything. Entitlement is
-- still decided in one place, by `canRead`, and the routes that write these tables
-- sit behind `requireUnitAccess` like every other per-book surface.

-- ---------------------------------------------------------------------------
-- reading_progress — where you are in a book
-- ---------------------------------------------------------------------------
-- One row per person per book, not per chapter: "where am I in this book" has
-- exactly one answer, and keeping one row means the library card needs one lookup
-- rather than a scan. Per-chapter furthest-read is recoverable from the bookmark
-- and annotation tables if it is ever wanted; inventing a row per chapter now
-- would be a table that mostly holds zeros.
--
-- `fraction` is 0..1 within `anchor_key`, and `chapters_done` counts how many
-- chapters were finished before it, so the card can say "62%" for the whole book
-- without reading the chapter table.
CREATE TABLE reading_progress (
  user_email    TEXT NOT NULL COLLATE NOCASE,
  slug          TEXT NOT NULL,
  anchor_key    TEXT NOT NULL,
  fraction      REAL NOT NULL DEFAULT 0 CHECK (fraction >= 0 AND fraction <= 1),
  chapters_done INTEGER NOT NULL DEFAULT 0,
  updated_at    TEXT NOT NULL,
  PRIMARY KEY (user_email, slug)
);

-- ---------------------------------------------------------------------------
-- bookmark — "put me back exactly here"
-- ---------------------------------------------------------------------------
-- Deliberately NOT the same thing as reading_progress. Progress is written
-- continuously and silently and is always overwritten; a bookmark is an act, it
-- is kept until removed, and there may be several in one chapter. Folding them
-- together would mean opening a book always returned you to the last place you
-- scrolled past rather than the place you chose to keep.
--
-- `id` is generated by the CLIENT, not by AUTOINCREMENT. A bookmark made with no
-- connection needs an identity before the server has seen it, or the outbox
-- cannot tell "create" from "create again".
--
-- `label` is the opening words of the marked block, copied at creation. Storing
-- it rather than looking it up means the list still reads correctly for a
-- bookmark whose text a re-compose has since changed — and that difference is
-- exactly what tells you the text moved.
CREATE TABLE bookmark (
  id          TEXT PRIMARY KEY NOT NULL,
  user_email  TEXT NOT NULL COLLATE NOCASE,
  slug        TEXT NOT NULL,
  anchor_key  TEXT NOT NULL,
  block_index INTEGER NOT NULL,
  label       TEXT NOT NULL,
  created_at  TEXT NOT NULL,
  deleted_at  TEXT
);

CREATE INDEX idx_bookmark_live ON bookmark (user_email, slug) WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- annotation — a highlight, optionally carrying a note
-- ---------------------------------------------------------------------------
-- One table, not two. A note is a highlight you also wrote on: making them
-- separate tables would mean a note could exist over no text, or two records
-- could claim the same passage and disagree about its colour.
--
-- HOW A PASSAGE IS IDENTIFIED, and why it is stored four ways:
--
--   block_index + start_offset/end_offset  — where it was
--   quote                                  — what it said
--   prefix                                 — what came just before it
--
-- The rendered HTML carries no per-paragraph ids (it is produced by
-- plan-dashboard's `renderMarkdown`, which the printed book also uses and which a
-- golden fixture pins — adding ids for this would change the print edition's
-- renderer). So the offsets locate the passage and the QUOTE is the authority: on
-- load the offsets are tried, and the text found there must equal `quote`. If it
-- does not, the quote is searched for in the chapter; a single hit re-anchors and
-- saves the correction, and anything else leaves the annotation intact but
-- unpainted and listed as "the text under this has changed". `prefix` is what
-- lets a phrase the book repeats be told apart from its twin.
--
-- Nothing is ever guessed onto a passage it did not come from. See
-- app/lib/anchor.ts, which owns that decision and is the only thing that makes it.
CREATE TABLE annotation (
  id           TEXT PRIMARY KEY NOT NULL,
  user_email   TEXT NOT NULL COLLATE NOCASE,
  slug         TEXT NOT NULL,
  anchor_key   TEXT NOT NULL,
  block_index  INTEGER NOT NULL,
  start_offset INTEGER NOT NULL,
  end_offset   INTEGER NOT NULL CHECK (end_offset > start_offset),
  quote        TEXT NOT NULL,
  prefix       TEXT NOT NULL DEFAULT '',
  colour       TEXT NOT NULL CHECK (colour IN ('gold', 'sage', 'sky', 'rose')),
  note         TEXT,
  created_at   TEXT NOT NULL,
  updated_at   TEXT NOT NULL,
  deleted_at   TEXT
);

CREATE INDEX idx_annotation_live ON annotation (user_email, slug) WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- listening_progress — where you are in an episode
-- ---------------------------------------------------------------------------
-- This replaces the `pf-positions` localStorage map in the player, which keyed on
-- the media SOURCE URL. That key is `media_asset.key`, which changes whenever an
-- episode's audio is re-uploaded under a new name — so a re-upload silently lost
-- every listener's place, and the loss was invisible because the old entry simply
-- never matched again. `(slug, number)` is the episode's own identity and survives
-- re-publishing exactly as `chapter.anchor_key` does.
CREATE TABLE listening_progress (
  user_email TEXT NOT NULL COLLATE NOCASE,
  slug       TEXT NOT NULL,
  number     INTEGER NOT NULL,
  seconds    INTEGER NOT NULL CHECK (seconds >= 0),
  updated_at TEXT NOT NULL,
  PRIMARY KEY (user_email, slug, number)
);

-- ---------------------------------------------------------------------------
-- A person has a name
-- ---------------------------------------------------------------------------
-- The admin screens listed raw email addresses because an address was all the
-- invite ever carried. Google supplies a display name on sign-in, but it arrives
-- only AFTER the person has signed in for the first time — and the whole point of
-- provisioning by email is that it happens before that. So the name is entered
-- with the invitation and belongs to the invitation.
--
-- Nullable, because every existing row predates the columns and because a name is
-- not required to give somebody access. Display falls back to `email_raw`.
ALTER TABLE invite ADD COLUMN first_name TEXT;
ALTER TABLE invite ADD COLUMN last_name TEXT;

-- ---------------------------------------------------------------------------
-- ...and a history of actually turning up
-- ---------------------------------------------------------------------------
-- `invite.redeemed_at` has existed since 0002 and NOTHING HAS EVER WRITTEN IT.
-- The column was declared, selected by `listPeople`, surfaced in the type, and
-- always null — so the admin screen could not distinguish someone who has been
-- reading for months from someone who never opened the link. That is precisely
-- the question "who have I invited and never heard from" asks, and it was
-- unanswerable.
--
-- It is stamped now in `session.create.before` (app/server/auth.server.ts), the
-- hook that already fires on every sign-in and already resolves the address.
-- `last_seen_at` goes with it: first arrival and most recent arrival are
-- different questions, and one column cannot answer both.
--
-- "Last seen" means last SIGN-IN, not last request. Sessions last thirty days
-- with a rolling refresh, so a daily reader stamps this about once a month. The
-- admin screen says "signed in" rather than "seen" for that reason — a label
-- claiming more precision than the data has is worse than no label.
ALTER TABLE invite ADD COLUMN last_seen_at TEXT;
