mindmap
  root(("Tasawwuf"))
    Obedience
      Follow Shariah commands
      Observe all prohibitions
    Compassion
      Purify soul of evils
      Adorn with noble traits
      Serve every creature