/**
 * book-md.ts — PUT /api/studio/book-md   body { slug, chapterKey, markdown }
 *
 * The Book Composer's chapter editor writes here. It replaces ONE chapter's body
 * in book/book.md — the composed reading edition the Composer previews — leaving
 * the `## Heading` line and every other chapter untouched. `chapterKey` is the
 * normalized heading key (mirrors lib/reader/composer.ts anchorKey); `markdown`
 * is the chapter body only (no heading), from the TipTap serializer.
 *
 * book.md is the last-mile reading edition. A save writes BOTH book.md (what the
 * Composer previews) and _system/composer-edits.json (the durable sidecar the
 * pipeline replays as its final compose step) — book.md alone is regenerated by
 * compose_book_v2 and would lose the edit. The prior file is kept as book.md.bak
 * (once) so the original is always recoverable.
 */
import type { APIRoute } from "astro";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { findContentDirSync } from "../../../lib/content-paths";
import { apiOk, apiError, apiServerError } from "../../../lib/api-responses";
import { writeChapterBody } from "../../../lib/reader/book-md-write";

export const prerender = false;

const SLUG_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

export const PUT: APIRoute = async ({ request }) => {
  let body: Record<string, unknown>;
  try {
    body = await request.json();
  } catch {
    return apiError("Invalid JSON body");
  }

  const slug = String(body.slug ?? "").trim();
  const chapterKey = String(body.chapterKey ?? "")
    .trim()
    .toLowerCase();
  const markdown = String(body.markdown ?? "").trim();

  if (!SLUG_RE.test(slug)) return apiError("Invalid slug");
  if (!chapterKey) return apiError("Missing chapterKey");
  if (!markdown) return apiError("Content is empty — nothing to save");

  const bookDir = findContentDirSync(slug);
  if (!bookDir) return apiError(`Book not found: ${slug}`, 404);
  const bookMd = join(bookDir, "book", "book.md");
  if (!existsSync(bookMd)) return apiError("book.md not found", 404);

  try {
    // The file surgery, the fence preservation and the durable sidecar all live in
    // ONE place now (lib/reader/book-md-write.ts) — the Arabic vowelling review
    // became a second caller, and "the Composer is the singular path for PDF-bound
    // chapter edits" only holds while there is a single function doing the writing.
    const res = writeChapterBody(bookDir, chapterKey, markdown);
    if (!res.ok) return apiError(res.error ?? "Save failed", 404);
    const { fences, sidecar } = res;

    return apiOk({ slug, chapterKey, path: bookMd, fences, sidecar });
  } catch (e) {
    return apiServerError(`Save failed: ${String(e)}`);
  }
};
