#!/usr/bin/env bash
# install-pipeline-w1.sh — machine-agnostic launchd manager for pipeline Wave 1
#
# Usage:
#   bash infra/launchd/install-pipeline-w1.sh install    # write plist + load
#   bash infra/launchd/install-pipeline-w1.sh start      # start or reinstall
#   bash infra/launchd/install-pipeline-w1.sh stop       # unload
#   bash infra/launchd/install-pipeline-w1.sh restart    # stop then start
#   bash infra/launchd/install-pipeline-w1.sh status     # show state
#   bash infra/launchd/install-pipeline-w1.sh logs       # tail logs
#   bash infra/launchd/install-pipeline-w1.sh uninstall  # stop + remove plist
set -euo pipefail

LABEL="com.podcast-factory.pipeline-w1"
UID_NUM="$(id -u)"
DOMAIN="gui/${UID_NUM}"

# Resolve repo root relative to this script — works on any machine/clone path
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

PYTHON3="/opt/homebrew/bin/python3"
if ! command -v "${PYTHON3}" >/dev/null 2>&1; then
    PYTHON3="$(command -v python3)"
fi

PLIST="${HOME}/Library/LaunchAgents/${LABEL}.plist"
OUT_LOG="${HOME}/Library/Logs/podcast-w1.log"
ERR_LOG="${HOME}/Library/Logs/podcast-w1.err"

write_plist() {
    mkdir -p "${HOME}/Library/LaunchAgents" "${HOME}/Library/Logs"
    cat >"${PLIST}" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by infra/launchd/install-pipeline-w1.sh — do not edit manually -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${LABEL}</string>

    <key>ProgramArguments</key>
    <array>
        <string>${PYTHON3}</string>
        <string>${REPO_ROOT}/scripts/podcast/run_wave.py</string>
        <string>1</string>
    </array>

    <key>WorkingDirectory</key>
    <string>${REPO_ROOT}</string>

    <key>StartInterval</key>
    <integer>3600</integer>

    <key>AbandonProcessGroup</key>
    <false/>

    <key>StandardOutPath</key>
    <string>${OUT_LOG}</string>

    <key>StandardErrorPath</key>
    <string>${ERR_LOG}</string>

    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/opt/homebrew/opt/python@3.11/bin:/usr/local/bin:/usr/bin:/bin</string>
    </dict>

    <key>RunAtLoad</key>
    <false/>
</dict>
</plist>
PLIST
    echo "Wrote plist: ${PLIST}"
    echo "  repo root: ${REPO_ROOT}"
    echo "  python3:   ${PYTHON3}"
    echo "  log out:   ${OUT_LOG}"
    echo "  log err:   ${ERR_LOG}"
}

is_loaded() {
    launchctl print "${DOMAIN}/${LABEL}" >/dev/null 2>&1
}

install_agent() {
    write_plist
    if is_loaded; then
        launchctl bootout "${DOMAIN}" "${PLIST}" >/dev/null 2>&1 || true
    fi
    launchctl bootstrap "${DOMAIN}" "${PLIST}"
    launchctl enable "${DOMAIN}/${LABEL}" >/dev/null 2>&1 || true
    echo "Loaded: ${LABEL}"
}

start_agent() {
    if ! is_loaded; then install_agent; return; fi
    launchctl kickstart -k "${DOMAIN}/${LABEL}"
}

stop_agent() {
    if is_loaded; then
        launchctl bootout "${DOMAIN}" "${PLIST}" >/dev/null 2>&1 || true
        echo "Unloaded: ${LABEL}"
    fi
}

status_agent() {
    echo "label: ${LABEL}"
    echo "plist: ${PLIST}"
    if is_loaded; then
        echo "state: loaded"
        launchctl print "${DOMAIN}/${LABEL}" | grep -E "state =|pid =|last exit code" || true
    else
        echo "state: not loaded"
    fi
    echo
    echo "logs:"
    echo "  stdout: ${OUT_LOG}"
    echo "  stderr: ${ERR_LOG}"
}

show_logs() {
    tail -n 120 "${OUT_LOG}" "${ERR_LOG}" 2>/dev/null || true
}

uninstall_agent() {
    stop_agent
    rm -f "${PLIST}"
    echo "Removed: ${PLIST}"
}

usage() {
    cat <<USAGE
Usage: $0 <install|start|stop|restart|status|logs|uninstall>

  install    Write machine-specific plist and load agent
  start      Start (reinstalls if not yet loaded)
  stop       Unload agent
  restart    Stop then start
  status     Show launchctl state + log paths
  logs       Tail stdout + stderr logs
  uninstall  Stop and remove plist from ~/Library/LaunchAgents/
USAGE
}

cmd="${1:-status}"
case "${cmd}" in
    install)   install_agent ;;
    start)     start_agent ;;
    stop)      stop_agent ;;
    restart)   stop_agent; start_agent ;;
    status)    status_agent ;;
    logs)      show_logs ;;
    uninstall) uninstall_agent ;;
    *)         usage; exit 1 ;;
esac
