mindmap
  root(("Lawful Animals"))
    Land Animals
      Camels cattle sheep wild
      Except fanged beasts of prey
    Birds
      All when slaughtered
      Except taloned birds of prey
    Sea Creatures
      Only caught alive with scales