mindmap
  root(("Blood money one thousand dinars"))
    Gold one thousand dinars
    Silver equal value
    Camels one hundred
    Cattle two hundred cows
    Sheep one thousand
    Cloth two hundred garments