"""_glossary_io.py — the ONE reader and the ONE writer for ``_system/glossary.yml``.

Why this module exists, measured 2026-08-02 on the live corpus:

    book                          fill_glossary_arabic   build_glossary
                                  .parse_glossary_yml    .read_existing_curation
    ayyuhal-walad (161 entries)             0                    0
    degrees-of-excellence (11)              0                    0
    the-master-and-the-disciple (74)        0                    0
    kitab-al-riyad (409)                  409                  400
    kunooz-al-hikmah (317)                317                  317

Three of five glossaries parsed as EMPTY by two of the three parsers that read
them. The file format had forked: `_annotation_policy.propose_annotation_policy`
began writing with ``yaml.safe_dump`` (``- phonetic: al-Naysaburi`` at column 0,
unquoted) while every hand-rolled parser matched only the emitted shape
(``  - phonetic: "al-Naysaburi"`` — two-space indent, quoted). Both are valid
YAML; neither reader used a YAML parser.

What that cost, all of it live before this module:

  * ``phases/audio_driver.py`` reads → classifies → WRITES BACK. On a fork-format
    book it wrote a glossary with ``entries:`` and nothing under it. Wrapped in a
    bare ``except`` and logged "non-blocking".
  * ``build_glossary --force`` (which phase 0c runs unconditionally) read zero
    curation and therefore discarded every hand-curated field — the exact loss
    ``_CURATED_FIELDS`` exists to prevent.
  * The Astro reader's glossary overlay was dark on all three books:
    ``lib/reader/glossary.ts`` required ``raw.startsWith("  - ")``.
  * ``emit_glossary_yml`` and its TypeScript twin ``emitGlossaryYaml`` both wrote
    a FIXED ALLOW-LIST of fields, so any round-trip silently dropped
    ``annotation_class`` / ``annotation_reason`` / ``english_equivalent`` — the
    annotation policy, destroyed by the act of reading and rewriting the file.

So: read with a real YAML parser (format-agnostic by construction — both shapes
are valid YAML, which is the whole reason the fork went unnoticed), and write ONE
shape, losslessly. "Losslessly" means every key present on the way in is present
on the way out. Never an allow-list: an allow-list is how the annotation policy
was lost, and the next field added elsewhere would be lost the same way.

The emitted shape is the LEGACY quoted one, not ``safe_dump``'s. Three Python
parsers and the TypeScript reader already speak it; ``safe_dump`` also reflows
long scalars, which turns every future glossary review into an unreadable diff.

NOT rewired: ``vowel_glossary.py``. It edits ``arabic_script:`` lines in place
and deliberately avoids the round-trip (see its own header). That is the right
call for a surgical single-field write and it is already safe.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

#: Emitted first, in this order, when present. Everything else follows in the
#: order it was read — the ordering is for diff readability, NOT a filter.
_LEAD_FIELDS = (
    "phonetic",
    "transliteration",
    "arabic_script",
    "audio_phonetic",
    "first_seen_snippet",
)

_HEADER = (
    "# Per-book glossary — phonetic <-> Arabic-script overlay for the reader.\n"
    "# Generated by scripts/podcast/build_glossary.py; arabic_script filled by\n"
    "# scripts/podcast/fill_glossary_arabic.py from _system/source/ocr/raw-extract.md.\n"
    "# Read and written through scripts/podcast/_glossary_io.py — the ONE reader and\n"
    "# the ONE writer. Unknown keys are preserved; do not add a field allow-list.\n"
)


def _q(value: Any) -> str:
    """Escape a scalar for a double-quoted YAML string.

    Newlines are escaped rather than emitted raw: a `first_seen_snippet` carrying
    one would otherwise terminate the scalar and every following line of that
    entry would parse as garbage.
    """
    return (
        str("" if value is None else value)
        .replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "")
    )


def load_glossary(path: Path) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    """``(entries, top_level_fields)``. Format-agnostic; order preserved.

    An absent file is ``([], {})`` — "nothing curated yet". An UNPARSEABLE file
    raises, and that asymmetry is deliberate: absent means new, malformed means
    something is wrong, and the failure that motivated this module was precisely
    a malformed-to-me file being read as empty and then written back.
    """
    if not path.exists():
        return [], {}
    doc = yaml.safe_load(path.read_text(encoding="utf-8"))
    if doc is None:
        return [], {}
    if not isinstance(doc, dict):
        raise ValueError(f"{path}: expected a mapping at the top level, got {type(doc).__name__}")
    entries = doc.get("entries") or []
    if not isinstance(entries, list):
        raise ValueError(f"{path}: 'entries' must be a list, got {type(entries).__name__}")
    top = {k: v for k, v in doc.items() if k != "entries"}
    return [dict(e) for e in entries if isinstance(e, dict)], top


def dump_glossary(entries: list[dict[str, Any]], top: dict[str, Any] | None = None) -> str:
    """Serialize to the canonical shape. Every key survives."""
    top = dict(top or {})
    out = [_HEADER, f"schema_version: {top.pop('schema_version', 1)}"]
    for key in sorted(top):
        out.append(f'{key}: "{_q(top[key])}"')
    out.append("entries:")
    for entry in entries:
        keys = [k for k in _LEAD_FIELDS if k in entry]
        keys += [k for k in entry if k not in _LEAD_FIELDS]
        if not keys:
            continue
        for i, key in enumerate(keys):
            value = entry[key]
            if isinstance(value, list):
                # A list-valued field (none today) would be destroyed by str().
                rendered = "[" + ", ".join(f'"{_q(v)}"' for v in value) + "]"
                line = f"{key}: {rendered}"
            else:
                line = f'{key}: "{_q(value)}"'
            out.append(("  - " if i == 0 else "    ") + line)
    return "\n".join(out) + "\n"


def save_glossary(path: Path, entries: list[dict[str, Any]], top: dict[str, Any] | None = None) -> None:
    """Write the canonical shape, creating the parent directory if needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(dump_glossary(entries, top), encoding="utf-8")


def normalize_glossary(path: Path) -> tuple[int, bool]:
    """Rewrite a glossary in the canonical shape. Returns ``(n_entries, changed)``."""
    entries, top = load_glossary(path)
    before = path.read_text(encoding="utf-8") if path.exists() else ""
    after = dump_glossary(entries, top)
    if after != before:
        path.write_text(after, encoding="utf-8")
    return len(entries), after != before


if __name__ == "__main__":  # pragma: no cover - thin CLI
    import sys

    args = [a for a in sys.argv[1:] if not a.startswith("-")]
    if not args:
        root = Path(__file__).resolve().parents[2] / "content"
        targets = sorted(root.glob("*/*/_system/glossary.yml")) + sorted(root.glob("*/*/*/_system/glossary.yml"))
    else:
        targets = [Path(a) for a in args]
    for target in targets:
        try:
            count, changed = normalize_glossary(target)
        except Exception as exc:  # noqa: BLE001 - report and continue the sweep
            print(f"  FAILED  {target}: {exc}", file=sys.stderr)
            continue
        print(f"  {'rewrote' if changed else 'already canonical':18s} {count:4d} entries  {target}")
    raise SystemExit(0)
