#!/usr/bin/env python3
"""build_glossary.py — derive BOOK_DIR/_system/glossary.yml from _phonetics.md.

PURPOSE

The podcast pipeline's Phase 0c emits _phonetics.md (a markdown table of
Arabic / proper-noun terms with transliteration + phonetic forms) so the
NotebookLM Customize prompt can steer host pronunciation. The chapters
uploaded to NotebookLM are phonetic-only by design (R-PHONETICS-OUT)
and never contain Arabic script.

For the podcast-reader app, however, we want to render the *original*
Arabic script alongside the phonetic form, on a header toggle. This
script materializes a per-book `glossary.yml` that the reader consumes:
each row pairs the phonetic form used in chapters with the Arabic
script, transliteration, and rendering metadata. The chapter `.txt`
files are unchanged; the glossary is overlaid at render-time.

INVOCATION

    python3 scripts/podcast/build_glossary.py \\
        --book-dir content/drafts/the-master-and-the-disciple

INPUTS

    BOOK_DIR/_system/source/text/_phonetics.md   (required)
    BOOK_DIR/_system/source/ocr/raw-extract.md   (optional — used only as
                                                   a script-source hint for
                                                   downstream LLM-fill)

OUTPUTS

    BOOK_DIR/_system/glossary.yml — per-book term overlay for the reader

The emitted YAML schema:

    - phonetic: Hujjah               # how the term renders in chapters/*.txt
      transliteration: Ḥujjah        # academic Latin transliteration
      arabic_script: ""              # Arabic native script; empty placeholder
                                     # until LLM-fill OR manual completion
      first_seen_snippet: "..."      # context from _phonetics.md (first match)

Reader behavior: when the "Show Arabic" header toggle is ON, the reader
scans rendered chapter prose for the `phonetic` value (case-insensitive,
word-boundary), and renders matches as
  "Hujjah <span dir=\"rtl\" lang=\"ar\">حُجَّة</span>"
or whatever the reader's chosen render mode dictates. Empty arabic_script
fields are no-ops (term renders phonetic-only — same as today).

LLM-FILL PROTOCOL (separate, not invoked here)

To populate the arabic_script fields, a follow-up script `fill_glossary
_arabic.py` shells out to `claude -p` once per book with the glossary
+ raw-extract.md as context. That step is deferred to avoid rate-limit
pressure on a running orchestrator and to give Asif a manual review gate
before any LLM cost. Approximate cost: ~$0.05-0.15 per book.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def parse_phonetics_md(path: Path) -> list[dict[str, str]]:
    """Parse the pipe-table at _phonetics.md into a list of row dicts.

    Expected header: | term | transliteration | phonetic | first-occurrence-snippet |
    """
    if not path.exists():
        return []
    lines = path.read_text(encoding="utf-8").splitlines()
    rows: list[dict[str, str]] = []
    header_seen = False
    for ln in lines:
        s = ln.strip()
        if not s.startswith("|"):
            continue
        if not header_seen:
            header_seen = True
            continue
        if set(s.replace("|", "").strip()) <= {"-", " ", ":"}:
            # divider row "|---|---|..."
            continue
        cells = [c.strip() for c in s.strip("|").split("|")]
        if len(cells) < 4:
            continue
        rows.append({
            "term": cells[0],
            "transliteration": cells[1],
            "phonetic": cells[2],
            "first_seen_snippet": cells[3],
        })
    return rows


def emit_glossary_yaml(rows: list[dict[str, str]]) -> str:
    """Emit YAML by hand to avoid a pip dependency on PyYAML.

    Keeps the order stable; quotes strings; escapes nothing fancy because
    the source is already markdown-table-sanitized.
    """
    lines: list[str] = []
    lines.append("# Per-book glossary — phonetic ↔ Arabic-script overlay for the reader.")
    lines.append("# Generated by scripts/podcast/build_glossary.py from _phonetics.md.")
    lines.append("# The arabic_script field is empty until a follow-up LLM-fill or")
    lines.append("# manual review populates it. Empty entries render phonetic-only")
    lines.append("# in the reader (no-op).")
    lines.append("")
    lines.append("schema_version: 1")
    lines.append("entries:")
    for r in rows:
        # Use the `term` column as the phonetic anchor for matching.
        # The `phonetic` column carries the hyphenated pronunciation guide
        # used inside the framing's Pronunciation section.
        phon = r["term"]
        translit = r["transliteration"]
        phon_audio = r["phonetic"]
        snippet = r["first_seen_snippet"]
        lines.append(f'  - phonetic: "{_q(phon)}"')
        lines.append(f'    transliteration: "{_q(translit)}"')
        lines.append(f'    arabic_script: ""')
        lines.append(f'    audio_phonetic: "{_q(phon_audio)}"')
        lines.append(f'    first_seen_snippet: "{_q(snippet)}"')
    return "\n".join(lines) + "\n"


def _q(s: str) -> str:
    """Escape `"` for YAML double-quoted strings; trim outer whitespace."""
    return s.replace("\\", "\\\\").replace('"', '\\"').strip()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    ap.add_argument("--book-dir", required=True, type=Path)
    ap.add_argument("--force", action="store_true",
                    help="Overwrite existing glossary.yml (drops any prior arabic_script fills).")
    args = ap.parse_args()

    book_dir: Path = args.book_dir.resolve()
    phonetics = book_dir / "_system" / "source" / "text" / "_phonetics.md"
    out_path = book_dir / "_system" / "glossary.yml"

    if not phonetics.exists():
        sys.stderr.write(
            f"_phonetics.md not found at {phonetics}\n"
            f"Run Phase 0c first (or scaffold the file manually).\n"
        )
        return 2

    if out_path.exists() and not args.force:
        sys.stderr.write(
            f"Refusing to overwrite {out_path} — pass --force to regenerate.\n"
            f"NOTE: --force drops any populated arabic_script values.\n"
        )
        return 3

    rows = parse_phonetics_md(phonetics)
    if not rows:
        sys.stderr.write(f"No rows parsed from {phonetics}\n")
        return 4

    out_path.write_text(emit_glossary_yaml(rows), encoding="utf-8")
    print(
        f"wrote {out_path.relative_to(book_dir)} — {len(rows)} entries "
        f"(arabic_script empty; fill via follow-up LLM step or manually)",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
