#!/usr/bin/env python3
"""fill_glossary_arabic.py — populate arabic_script in BOOK_DIR/_system/glossary.yml.

PURPOSE

`build_glossary.py` emits a glossary.yml scaffold from _phonetics.md with
every `arabic_script` field empty. This script fires one `claude -p` call
per book with the empty glossary + the Arabic OCR raw-extract as context,
and writes the populated glossary back to disk. Idempotent: re-running
on an already-populated glossary is a no-op unless --force is passed.

INVOCATION

    python3 scripts/podcast/fill_glossary_arabic.py \\
        --book-dir content/drafts/the-master-and-the-disciple [--force]

INPUTS

    BOOK_DIR/_system/glossary.yml                  (required)
    BOOK_DIR/_system/source/ocr/raw-extract.md     (preferred) OR
    BOOK_DIR/_system/source/text/raw-extract.md    (fallback for books
                                                     whose Phase 0a wrote
                                                     the Arabic OCR directly
                                                     to the text/ folder)

OUTPUT

    BOOK_DIR/_system/glossary.yml — same file, with arabic_script filled.

COST

    One claude -p call per book (Sonnet by default — Arabic script extraction
    is content-recognition, not deep reasoning). Approximate spend: $0.05–0.15
    depending on glossary size + OCR length. Cost is logged to the book's
    _system/cost-ledger.jsonl.

INVARIANTS

    - Entries with an existing non-empty arabic_script are PRESERVED unless
      --force is passed. The LLM is instructed to only emit fills for the
      empty rows.
    - Output YAML preserves the original entry order from the input.
    - If the LLM emits a row that doesn't exist in the input, it is dropped
      with a warning. Hallucinations don't get committed.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import time
from pathlib import Path

# Re-use the same YAML escaping convention as build_glossary.py.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_glossary import _q  # noqa: E402

CLAUDE_CMD = "claude"
CLAUDE_TIMEOUT_S = 600  # 10 min — comfortable for ~75 terms + small OCR file
MODEL = "claude-sonnet-4-6"


def parse_glossary_yml(path: Path) -> tuple[list[dict[str, str]], dict[str, object]]:
    """Parse the YAML emitted by build_glossary.py (no PyYAML dependency).

    Returns (entries, top_level_fields). Entries preserve order.
    """
    text = path.read_text(encoding="utf-8")
    entries: list[dict[str, str]] = []
    top: dict[str, object] = {}
    current: dict[str, str] | None = None
    in_entries = False
    for raw in text.splitlines():
        if raw.startswith("#") or not raw.strip():
            continue
        if raw.startswith("entries:"):
            in_entries = True
            continue
        if not in_entries:
            # top-level scalar
            m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$", raw)
            if m:
                top[m.group(1)] = m.group(2).strip()
            continue
        if raw.startswith("  - "):
            # new entry
            if current is not None:
                entries.append(current)
            current = {}
            key_val = raw[4:]
            k, _, v = key_val.partition(":")
            current[k.strip()] = _unq(v.strip())
        elif raw.startswith("    "):
            k, _, v = raw[4:].partition(":")
            if current is not None:
                current[k.strip()] = _unq(v.strip())
    if current is not None:
        entries.append(current)
    return entries, top


def _unq(s: str) -> str:
    """Strip outer double-quotes and unescape; matches build_glossary._q's inverse."""
    if len(s) >= 2 and s[0] == '"' and s[-1] == '"':
        s = s[1:-1]
    return s.replace('\\"', '"').replace("\\\\", "\\")


def emit_glossary_yml(entries: list[dict[str, str]], top: dict[str, object]) -> str:
    """Round-trip the YAML in the same shape build_glossary.py emits."""
    lines: list[str] = []
    lines.append("# Per-book glossary — phonetic ↔ Arabic-script overlay for the reader.")
    lines.append("# Generated by scripts/podcast/build_glossary.py; arabic_script filled by")
    lines.append("# scripts/podcast/fill_glossary_arabic.py from _system/source/ocr/raw-extract.md.")
    lines.append("")
    lines.append(f"schema_version: {top.get('schema_version', 1)}")
    lines.append("entries:")
    for r in entries:
        lines.append(f'  - phonetic: "{_q(r.get("phonetic", ""))}"')
        lines.append(f'    transliteration: "{_q(r.get("transliteration", ""))}"')
        lines.append(f'    arabic_script: "{_q(r.get("arabic_script", ""))}"')
        lines.append(f'    audio_phonetic: "{_q(r.get("audio_phonetic", ""))}"')
        lines.append(f'    first_seen_snippet: "{_q(r.get("first_seen_snippet", ""))}"')
    return "\n".join(lines) + "\n"


def build_prompt(empty_rows: list[dict[str, str]], ocr_text: str) -> str:
    rows_block = "\n".join(
        f'  - phonetic: "{r["phonetic"]}"  transliteration: "{r["transliteration"]}"  '
        f'first_seen_snippet: "{r["first_seen_snippet"]}"'
        for r in empty_rows
    )
    return (
        "You are filling in the Arabic-script column of a podcast-book glossary. "
        "For each row below, identify the Arabic script that the phonetic + "
        "transliteration + first-occurrence-snippet refer to, by searching the "
        "OCR text appended at the end.\n\n"
        "OUTPUT FORMAT — strict; one entry per row, in input order:\n"
        "  - phonetic: \"<verbatim from input>\"\n"
        "    arabic_script: \"<the Arabic script as it appears in the OCR; "
        "preserve diacritics + spacing>\"\n\n"
        "RULES\n"
        "  1. Phonetic value MUST match the input verbatim (used for join).\n"
        "  2. If you cannot find a confident match in the OCR, set arabic_script "
        "to the EMPTY string \"\" — do not guess. Empty fields stay empty in the "
        "glossary.\n"
        "  3. Do NOT emit any row whose phonetic is not in the input.\n"
        "  4. Do NOT emit prose around the YAML. Just the YAML block.\n"
        "  5. Entry order matches input order.\n\n"
        f"INPUT ROWS ({len(empty_rows)}):\n{rows_block}\n\n"
        f"OCR TEXT (Arabic source; page-marker lines prefixed with `<!-- page N -->`):\n"
        f"{ocr_text}\n"
    )


def parse_llm_yaml(raw: str) -> dict[str, str]:
    """Parse the LLM's output into {phonetic: arabic_script}. Ignores hallucinations."""
    out: dict[str, str] = {}
    current_phon: str | None = None
    for line in raw.splitlines():
        s = line.strip()
        if s.startswith('- phonetic:'):
            current_phon = _unq(s[len("- phonetic:"):].strip())
        elif s.startswith('arabic_script:') and current_phon is not None:
            val = _unq(s[len("arabic_script:"):].strip())
            out[current_phon] = val
            current_phon = None
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    ap.add_argument("--book-dir", required=True, type=Path)
    ap.add_argument("--force", action="store_true",
                    help="Re-fill entries that already have arabic_script populated.")
    ap.add_argument("--dry-run", action="store_true",
                    help="Print the prompt that would be sent; do not call the LLM.")
    args = ap.parse_args()

    book_dir: Path = args.book_dir.resolve()
    glossary_path = book_dir / "_system" / "glossary.yml"
    ocr_candidates = [
        book_dir / "_system" / "source" / "ocr" / "raw-extract.md",
        book_dir / "_system" / "source" / "text" / "raw-extract.md",
    ]
    ocr_path = next((p for p in ocr_candidates if p.exists()), None)
    if not glossary_path.exists():
        sys.stderr.write(f"glossary.yml not found at {glossary_path}\n"
                         f"Run scripts/podcast/build_glossary.py first.\n")
        return 2
    if ocr_path is None:
        sys.stderr.write(f"raw-extract.md not found in either:\n  {ocr_candidates[0]}\n  {ocr_candidates[1]}\n")
        return 3

    entries, top = parse_glossary_yml(glossary_path)
    if args.force:
        empty = entries
    else:
        empty = [r for r in entries if not r.get("arabic_script", "")]
    if not empty:
        print(f"all {len(entries)} entries already have arabic_script — nothing to fill", file=sys.stderr)
        return 0

    ocr_text = ocr_path.read_text(encoding="utf-8")
    prompt = build_prompt(empty, ocr_text)

    if args.dry_run:
        print(prompt)
        return 0

    print(f"calling {MODEL} for {len(empty)} entries (OCR {len(ocr_text):,} chars) …", file=sys.stderr)
    t0 = time.monotonic()
    try:
        result = subprocess.run(
            [CLAUDE_CMD, "-p", "--model", MODEL, prompt],
            capture_output=True,
            text=True,
            timeout=CLAUDE_TIMEOUT_S,
        )
    except subprocess.TimeoutExpired:
        sys.stderr.write(f"LLM call exceeded {CLAUDE_TIMEOUT_S}s timeout\n")
        return 4
    elapsed = time.monotonic() - t0
    if result.returncode != 0:
        sys.stderr.write(f"claude -p failed (rc={result.returncode}):\n{result.stderr[:600]}\n")
        return 5

    fills = parse_llm_yaml(result.stdout)
    print(f"  → LLM returned {len(fills)} fills in {elapsed:.1f}s", file=sys.stderr)

    # Merge fills into entries (preserve order, ignore unknown phonetics)
    by_phon = {r["phonetic"]: r for r in entries}
    n_filled = 0
    n_skipped_unknown = 0
    for phon, script in fills.items():
        if phon not in by_phon:
            n_skipped_unknown += 1
            continue
        if script:  # only update on non-empty
            by_phon[phon]["arabic_script"] = script
            n_filled += 1

    if n_skipped_unknown:
        print(f"  ⚠ {n_skipped_unknown} LLM-emitted rows had unknown phonetics; dropped", file=sys.stderr)

    glossary_path.write_text(emit_glossary_yml(entries, top), encoding="utf-8")
    print(f"wrote {glossary_path.relative_to(book_dir)} — {n_filled} entries filled "
          f"(total non-empty: {sum(1 for r in entries if r.get('arabic_script', ''))})",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
