#!/usr/bin/env python3
"""learn_aggregate.py — fold _learning/findings.jsonl into _learning/patterns.md.

PURPOSE

  Stage 2 of the podcast-skill learning pipeline (sense → AGGREGATE → propose
  → test → promote). Reads the append-only findings ledger, groups records by
  `signature`, and emits a deterministic markdown report listing every
  signature with its occurrence count, distinct books, distinct episodes,
  first-seen / last-seen timestamps, and the severity it carries.

  Output is overwritten every run. Stable, byte-deterministic given the same
  input ledger.

USAGE

  python3 scripts/podcast/learn_aggregate.py

  Optional flag:
    --ledger <path>   Use a non-default ledger location (for testing).

OUTPUT

  Writes content/podcast/.skill/_learning/patterns.md.

DOES NOT MODIFY the ledger. Read-only against findings.jsonl.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path
from _paths import REPO_ROOT
from typing import Any

DEFAULT_LEDGER = REPO_ROOT / "content/podcast/.skill/_learning/findings.jsonl"
OUTPUT_PATH = REPO_ROOT / "content/podcast/.skill/_learning/patterns.md"

# Aggregation thresholds — a pattern is "recurring" (proposer-eligible) when
# it crosses EITHER threshold. Single occurrences are still recorded but
# tagged so the proposer ignores them.
THRESHOLD_BOOKS = 2      # appears in ≥ 2 distinct books
THRESHOLD_EPISODES = 3   # appears in ≥ 3 distinct episodes
THRESHOLD_DENSITY = 3    # check_id fires ≥ 3× in same (book, episode)


def load_ledger(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    records: list[dict[str, Any]] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        raw = raw.strip()
        if not raw:
            continue
        try:
            records.append(json.loads(raw))
        except json.JSONDecodeError as e:
            print(f"WARN: skipping malformed ledger line: {e}", file=sys.stderr)
    return records


def group_by_signature(records: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    out: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for r in records:
        sig = r.get("signature", "")
        if sig:
            out[sig].append(r)
    return out


def aggregate(records: list[dict[str, Any]]) -> str:
    groups = group_by_signature(records)
    if not groups:
        return (
            "# Podcast Learning — Patterns\n\n"
            "_No findings in the ledger yet._\n"
        )

    # In-book density groupings (check_id, book, episode) → records
    density: dict[tuple[str, str, str], int] = defaultdict(int)
    for r in records:
        check = r.get("check_id", "")
        book = r.get("book", "")
        ep = r.get("episode", "")
        if check and book:
            density[(check, book, ep)] += 1

    rows: list[tuple[str, int, int, int, str, str, str, str]] = []
    for sig, recs in groups.items():
        count = len(recs)
        books = sorted({r.get("book", "") for r in recs if r.get("book")})
        episodes = sorted({r.get("episode", "") for r in recs if r.get("episode")})
        ts_values = sorted([r.get("ts", "") for r in recs if r.get("ts")])
        severity = recs[0].get("severity", "")
        check_id = recs[0].get("check_id", "")
        rows.append((
            sig,
            count,
            len(books),
            len(episodes),
            ts_values[0] if ts_values else "",
            ts_values[-1] if ts_values else "",
            severity,
            check_id,
        ))

    rows.sort(key=lambda r: (-r[1], r[0]))

    lines: list[str] = []
    lines.append("# Podcast Learning — Patterns")
    lines.append("")
    lines.append(
        f"**Generated by:** `scripts/podcast/learn_aggregate.py` "
        f"(ledger: `{DEFAULT_LEDGER.relative_to(REPO_ROOT)}`)"
    )
    lines.append(f"**Total records:** {len(records)} · **Distinct signatures:** {len(groups)}")
    lines.append(
        f"**Proposer thresholds:** ≥ {THRESHOLD_BOOKS} books OR ≥ {THRESHOLD_EPISODES} episodes "
        f"OR ≥ {THRESHOLD_DENSITY} firings of same check in same (book, episode)"
    )
    lines.append("")

    # Source breakdown — surfaces how many findings came from each Challenger.
    # podcast-challenger (audio) and slide-deck-challenger (visual) co-tenant
    # the same ledger; this section makes the split visible at a glance.
    source_counts: dict[str, int] = defaultdict(int)
    for r in records:
        source_counts[r.get("source", "unknown")] += 1
    if len(source_counts) > 1 or (source_counts and "unknown" not in source_counts):
        lines.append("## By source")
        lines.append("")
        for src in sorted(source_counts):
            lines.append(f"- `{src}` — {source_counts[src]} record(s)")
        lines.append("")

    lines.append("## Signatures (sorted by occurrence)")
    lines.append("")
    lines.append("| Signature | Count | Books | Episodes | Severity | Check | First seen | Last seen | Proposer-eligible |")
    lines.append("|---|---|---|---|---|---|---|---|---|")
    for sig, count, n_books, n_eps, ts_first, ts_last, sev, check in rows:
        eligible = (
            n_books >= THRESHOLD_BOOKS
            or n_eps >= THRESHOLD_EPISODES
        )
        flag = "**Y**" if eligible else "n"
        lines.append(
            f"| `{sig}` | {count} | {n_books} | {n_eps} | {sev} | {check} | "
            f"{ts_first} | {ts_last} | {flag} |"
        )
    lines.append("")
    # Density section — surfaces (check_id, book, episode) tuples that crossed
    # the density threshold; these are the "tighten this check" candidates.
    dense_rows = [(k, n) for k, n in density.items() if n >= THRESHOLD_DENSITY]
    if dense_rows:
        dense_rows.sort(key=lambda x: -x[1])
        lines.append("## In-book density (≥ density threshold)")
        lines.append("")
        lines.append("Recurring same-check findings against one artifact. Strong learning signal even before cross-book recurrence.")
        lines.append("")
        lines.append("| Check | Book | Episode | Firings |")
        lines.append("|---|---|---|---|")
        for (check, book, ep), n in dense_rows:
            lines.append(f"| `{check}` | `{book}` | `{ep}` | **{n}** |")
        lines.append("")
    lines.append("## How to read this")
    lines.append("")
    lines.append(
        "- **Count** is total ledger records for the signature; it can include the same finding "
        "carried across multiple runs (deduped by signature, not by ts)."
    )
    lines.append(
        "- **Books** and **Episodes** are distinct counts. A signature seen in one book but four "
        "episodes is still proposer-eligible (≥3 episodes); a signature seen in two books at one "
        "episode each is also eligible (≥2 books)."
    )
    lines.append(
        "- **Proposer-eligible = Y** means `learn_propose.py` will emit a proposal markdown for "
        "this signature on its next run. The human still has to accept or reject."
    )
    return "\n".join(lines) + "\n"


def _parse_since(spec: str | None) -> "datetime | None":
    """F33 (2026-05-25): convert '7d', '30d', '24h', '4w', '2m' to cutoff dt."""
    if not spec:
        return None
    import re as _re
    from datetime import datetime, timedelta, timezone
    m = _re.match(r"^(\d+)([dhwm])$", spec.strip().lower())
    if not m:
        return None
    n, unit = int(m.group(1)), m.group(2)
    deltas = {"d": timedelta(days=n), "h": timedelta(hours=n),
              "w": timedelta(weeks=n), "m": timedelta(days=30 * n)}
    return datetime.now(timezone.utc) - deltas[unit]


def _filter_since(records: list[dict[str, Any]], since: "datetime | None") -> list[dict[str, Any]]:
    """F33: keep only records with ts >= cutoff. ts is ISO-8601 UTC."""
    if not since:
        return records
    from datetime import datetime
    out: list[dict[str, Any]] = []
    for r in records:
        ts = r.get("ts", "")
        try:
            rec_dt = datetime.fromisoformat(ts.replace("Z", "+00:00"))
        except ValueError:
            continue
        if rec_dt >= since:
            out.append(r)
    return out


def by_check_id_report(records: list[dict[str, Any]], since_label: str) -> str:
    """F33 (2026-05-25): rule-firing telemetry — count records per check_id,
    severity, and book; rank by frequency. Lets the operator see which rules
    fire most in the last N days — a signal for which rule deserves
    deterministic codification, deprecation, or rubric refinement."""
    from collections import Counter
    by_check: Counter = Counter()
    by_check_sev: dict[str, Counter] = {}
    by_check_book: dict[str, Counter] = {}
    for r in records:
        cid = r.get("check_id", "")
        sev = r.get("severity", "?")
        book = r.get("book", "?")
        if not cid:
            continue
        by_check[cid] += 1
        by_check_sev.setdefault(cid, Counter())[sev] += 1
        by_check_book.setdefault(cid, Counter())[book] += 1

    lines = [
        f"# Rule-firing telemetry — window: {since_label}",
        "",
        f"Records analyzed: **{len(records)}**.",
        f"Distinct check_ids firing: **{len(by_check)}**.",
        "",
        "| Rank | check_id | Total fires | P0 | P1 | P2 | Books affected | Top book |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for rank, (cid, total) in enumerate(by_check.most_common(50), 1):
        sevs = by_check_sev.get(cid, Counter())
        books = by_check_book.get(cid, Counter())
        top_book, top_count = (books.most_common(1) or [("—", 0)])[0]
        lines.append(
            f"| {rank} | `{cid}` | {total} | {sevs.get('P0', 0)} | "
            f"{sevs.get('P1', 0)} | {sevs.get('P2', 0)} | "
            f"{len(books)} | `{top_book}` ({top_count}) |"
        )
    if not by_check:
        lines.append("| — | _(no records in window)_ | — | — | — | — | — | — |")
    return "\n".join(lines) + "\n"


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--ledger", type=Path, default=DEFAULT_LEDGER,
                   help=f"Path to findings.jsonl (default: {DEFAULT_LEDGER})")
    p.add_argument("--output", type=Path, default=OUTPUT_PATH,
                   help=f"Path to patterns.md (default: {OUTPUT_PATH})")
    p.add_argument("--since", type=str, default=None,
                   help="F33: time window for --by-check-id (e.g. 7d, 30d, 4w, 2m). Default: all-time.")
    p.add_argument("--by-check-id", action="store_true",
                   help="F33: emit rule-firing telemetry report (stdout) instead of patterns.md.")
    args = p.parse_args()

    records = load_ledger(args.ledger)
    if args.by_check_id:
        since = _parse_since(args.since)
        records = _filter_since(records, since)
        sys.stdout.write(by_check_id_report(records, args.since or "all-time"))
        return 0
    content = aggregate(records)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    print(f"Wrote patterns: {args.output.relative_to(REPO_ROOT) if REPO_ROOT in args.output.parents else args.output}")
    print(f"  {len(records)} records → {content.count(chr(10).join(['', '|']) ) // 1} (table rows summarize signatures)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
