#!/usr/bin/env python3
"""learn_aggregate.py — fold _learning/findings.jsonl into _learning/patterns.md.

PURPOSE

  Stage 2 of the podcast-skill learning pipeline (sense → AGGREGATE → propose
  → test → promote). Reads the append-only findings ledger, groups records by
  `signature`, and emits a deterministic markdown report listing every
  signature with its occurrence count, distinct books, distinct episodes,
  first-seen / last-seen timestamps, and the severity it carries.

  Output is overwritten every run. Stable, byte-deterministic given the same
  input ledger.

USAGE

  python3 scripts/podcast/learn_aggregate.py

  Optional flag:
    --ledger <path>   Use a non-default ledger location (for testing).

OUTPUT

  Writes content/podcast/.skill/_learning/patterns.md.

DOES NOT MODIFY the ledger. Read-only against findings.jsonl.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_LEDGER = REPO_ROOT / "content/podcast/.skill/_learning/findings.jsonl"
OUTPUT_PATH = REPO_ROOT / "content/podcast/.skill/_learning/patterns.md"

# Aggregation thresholds — a pattern is "recurring" (proposer-eligible) when
# it crosses EITHER threshold. Single occurrences are still recorded but
# tagged so the proposer ignores them.
THRESHOLD_BOOKS = 2     # appears in ≥ 2 distinct books
THRESHOLD_EPISODES = 3  # appears in ≥ 3 distinct episodes


def load_ledger(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    records: list[dict[str, Any]] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        raw = raw.strip()
        if not raw:
            continue
        try:
            records.append(json.loads(raw))
        except json.JSONDecodeError as e:
            print(f"WARN: skipping malformed ledger line: {e}", file=sys.stderr)
    return records


def group_by_signature(records: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    out: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for r in records:
        sig = r.get("signature", "")
        if sig:
            out[sig].append(r)
    return out


def aggregate(records: list[dict[str, Any]]) -> str:
    groups = group_by_signature(records)
    if not groups:
        return (
            "# Podcast Learning — Patterns\n\n"
            "_No findings in the ledger yet._\n"
        )

    rows: list[tuple[str, int, int, int, str, str, str, str]] = []
    for sig, recs in groups.items():
        count = len(recs)
        books = sorted({r.get("book", "") for r in recs if r.get("book")})
        episodes = sorted({r.get("episode", "") for r in recs if r.get("episode")})
        ts_values = sorted([r.get("ts", "") for r in recs if r.get("ts")])
        severity = recs[0].get("severity", "")
        check_id = recs[0].get("check_id", "")
        rows.append((
            sig,
            count,
            len(books),
            len(episodes),
            ts_values[0] if ts_values else "",
            ts_values[-1] if ts_values else "",
            severity,
            check_id,
        ))

    rows.sort(key=lambda r: (-r[1], r[0]))

    lines: list[str] = []
    lines.append("# Podcast Learning — Patterns")
    lines.append("")
    lines.append(
        f"**Generated by:** `scripts/podcast/learn_aggregate.py` "
        f"(ledger: `{DEFAULT_LEDGER.relative_to(REPO_ROOT)}`)"
    )
    lines.append(f"**Total records:** {len(records)} · **Distinct signatures:** {len(groups)}")
    lines.append(
        f"**Proposer thresholds:** ≥ {THRESHOLD_BOOKS} books OR ≥ {THRESHOLD_EPISODES} episodes"
    )
    lines.append("")
    lines.append("## Signatures (sorted by occurrence)")
    lines.append("")
    lines.append("| Signature | Count | Books | Episodes | Severity | Check | First seen | Last seen | Proposer-eligible |")
    lines.append("|---|---|---|---|---|---|---|---|---|")
    for sig, count, n_books, n_eps, ts_first, ts_last, sev, check in rows:
        eligible = (n_books >= THRESHOLD_BOOKS) or (n_eps >= THRESHOLD_EPISODES)
        flag = "**Y**" if eligible else "n"
        lines.append(
            f"| `{sig}` | {count} | {n_books} | {n_eps} | {sev} | {check} | "
            f"{ts_first} | {ts_last} | {flag} |"
        )
    lines.append("")
    lines.append("## How to read this")
    lines.append("")
    lines.append(
        "- **Count** is total ledger records for the signature; it can include the same finding "
        "carried across multiple runs (deduped by signature, not by ts)."
    )
    lines.append(
        "- **Books** and **Episodes** are distinct counts. A signature seen in one book but four "
        "episodes is still proposer-eligible (≥3 episodes); a signature seen in two books at one "
        "episode each is also eligible (≥2 books)."
    )
    lines.append(
        "- **Proposer-eligible = Y** means `learn_propose.py` will emit a proposal markdown for "
        "this signature on its next run. The human still has to accept or reject."
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--ledger", type=Path, default=DEFAULT_LEDGER,
                   help=f"Path to findings.jsonl (default: {DEFAULT_LEDGER})")
    p.add_argument("--output", type=Path, default=OUTPUT_PATH,
                   help=f"Path to patterns.md (default: {OUTPUT_PATH})")
    args = p.parse_args()

    records = load_ledger(args.ledger)
    content = aggregate(records)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    print(f"Wrote patterns: {args.output.relative_to(REPO_ROOT) if REPO_ROOT in args.output.parents else args.output}")
    print(f"  {len(records)} records → {content.count(chr(10).join(['', '|']) ) // 1} (table rows summarize signatures)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
