/**
 * Regenerate `.dev.vars` from the macOS keychain.
 *
 * `.dev.vars` is gitignored, so a fresh clone has no local secrets and no way to
 * re-derive them. Rather than leave that as a note in a README, the durable copy
 * lives in the keychain — the same pattern cf-deploy.sh already uses for the
 * Cloudflare token — and this script rebuilds the file from it.
 *
 * Two rules it follows, both deliberate:
 *
 *   - It never PRINTS a secret. It reads with `security find-generic-password -w`
 *     and writes straight to the file. Nothing lands in scrollback.
 *   - It never WRITES to the keychain. Asif stores and rotates values himself
 *     with `security add-generic-password -w`, which prompts — so the value never
 *     enters shell history either. If an item is missing this prints the exact
 *     command and stops.
 *
 *   node scripts/dev-vars.mjs           # rebuild .dev.vars
 *   node scripts/dev-vars.mjs --check   # report what is present; write nothing
 */
import { execFileSync } from "node:child_process";
import { chmodSync, writeFileSync } from "node:fs";

/** Local dev is the only consumer; production uses `wrangler secret put`. */
const ITEMS = [
  {
    name: "BETTER_AUTH_SECRET",
    service: "listener_better_auth_secret",
    why: "signs the session cookie",
    generate: "openssl rand -base64 32",
  },
  {
    name: "GOOGLE_CLIENT_SECRET",
    service: "safina_google_client_secret",
    why: "the Safina OAuth client secret, from the Google Cloud console",
    generate: null,
  },
];

const check = process.argv.includes("--check");

/** @param {string} service @returns {string | null} */
function fromKeychain(service) {
  try {
    return execFileSync("security", ["find-generic-password", "-s", service, "-w"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return null;
  }
}

/** @param {string} service */
function exists(service) {
  try {
    // No -w: an existence check that cannot read the value.
    execFileSync("security", ["find-generic-password", "-s", service], { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
}

const missing = ITEMS.filter((item) => !exists(item.service));

if (missing.length > 0) {
  console.error("Missing keychain items:\n");
  for (const item of missing) {
    console.error(`  ${item.name} — ${item.why}`);
    console.error(
      item.generate
        ? // Command substitution: shell history keeps the literal text, so the
          // generated value is never recorded and never shown on screen.
          `    store:  security add-generic-password -U -a "$USER" ` +
            `-s ${item.service} -w "$(${item.generate})"\n`
        : `    store:  security add-generic-password -U -a "$USER" -s ${item.service} -w\n` +
            `            (prompts for the value, so it never enters shell history)\n`,
    );
  }
  process.exit(1);
}

if (check) {
  for (const item of ITEMS) console.log(`  ok  ${item.name}  (keychain: ${item.service})`);
  console.log("\nAll keychain items present. Run without --check to rebuild .dev.vars.");
  process.exit(0);
}

// GOOGLE_CLIENT_ID is deliberately NOT here: a client id is public — it travels
// in the browser's address bar during sign-in — so it belongs in wrangler.jsonc
// under `vars`, where it is visible and reviewable, not in a secrets file.
const lines = [
  "# GENERATED by scripts/dev-vars.mjs from the macOS keychain. Do not hand-edit.",
  "# Gitignored. Rebuild any time with: npm run dev-vars",
  "",
  "# Local override — production uses the value in wrangler.jsonc.",
  "BETTER_AUTH_URL=http://localhost:5273",
  "",
  ...ITEMS.map((item) => `${item.name}=${fromKeychain(item.service)}`),
  "",
];

// chmod SEPARATELY: writeFileSync's `mode` applies only when it creates the
// file, so rewriting an existing .dev.vars silently keeps whatever mode it had —
// 644 by default, i.e. world-readable. Caught on the first real run.
writeFileSync(".dev.vars", lines.join("\n"));
chmodSync(".dev.vars", 0o600);
console.log(`.dev.vars rebuilt from the keychain (${ITEMS.length} secrets, mode 600).`);
